/** Fictional admin display records. They never enter the knowledge base or any index. */
export type AssetKind = "classics" | "rules" | "evidence";
export type AssetRecord = {
  id: string;
  name: string;
  domain: string;
  state: string;
  level: string;
  detail: string;
  secondary: string;
  count: string;
  updated: string;
};
export const assets: Record<AssetKind, AssetRecord[]> = {
  classics: [
    {
      id: "DEMO-B001",
      name: "增删卜易",
      domain: "六爻",
      state: "已审选段",
      level: "C",
      detail: "本轮演示记录 · 非真实资产",
      secondary: "动变章、世应章等",
      count: "12 章",
      updated: "10-02 09:12",
    },
    {
      id: "DEMO-B002",
      name: "卜筮正宗",
      domain: "六爻",
      state: "待复核",
      level: "C",
      detail: "章节校核的视觉示例",
      secondary: "纳甲、六亲相关章节",
      count: "18 章",
      updated: "10-02 08:36",
    },
    {
      id: "DEMO-B003",
      name: "周易",
      domain: "周易",
      state: "已审选段",
      level: "C",
      detail: "卦爻正文的视觉示例",
      secondary: "卦辞、爻辞",
      count: "64 卦",
      updated: "10-01 16:20",
    },
    {
      id: "DEMO-B004",
      name: "紫微斗数全书",
      domain: "紫微",
      state: "待复核",
      level: "C",
      detail: "保留安星疑文的视觉示例",
      secondary: "安星相关选段",
      count: "8 章",
      updated: "10-01 14:45",
    },
    {
      id: "DEMO-B005",
      name: "六壬大全",
      domain: "六壬",
      state: "已审选段",
      level: "C",
      detail: "九宗门章节的视觉示例",
      secondary: "取传相关选段",
      count: "9 章",
      updated: "09-30 11:05",
    },
    {
      id: "DEMO-B006",
      name: "待核电子文本",
      domain: "风水",
      state: "隔离",
      level: "D",
      detail: "隔离资产的虚构占位记录，无实际原文",
      secondary: "待核版本与来源",
      count: "—",
      updated: "09-30 10:30",
    },
  ],
  rules: [
    {
      id: "DEMO-R001",
      name: "动爻与变卦",
      domain: "六爻",
      state: "示例可执行",
      level: "C",
      detail: "示意：逐爻阴阳变化与本变卦结构",
      secondary: "京房八宫 · 示例约定",
      count: "2 条依据",
      updated: "10-02 09:12",
    },
    {
      id: "DEMO-R002",
      name: "八宫世应定位",
      domain: "六爻",
      state: "示例可执行",
      level: "C",
      detail: "示意：本卦所属宫与世应位置",
      secondary: "京房八宫 · 示例约定",
      count: "3 条依据",
      updated: "10-02 08:36",
    },
    {
      id: "DEMO-R003",
      name: "四课取传次序",
      domain: "六壬",
      state: "待复核",
      level: "C",
      detail: "示意：流派与优先级需显式关联",
      secondary: "九宗门 · 示例约定",
      count: "2 条依据",
      updated: "10-01 16:20",
    },
    {
      id: "DEMO-R004",
      name: "二十四山分区",
      domain: "风水",
      state: "示例可执行",
      level: "C",
      detail: "示意：半开角度区间与方位关系",
      secondary: "角度定位 · 示例约定",
      count: "1 条依据",
      updated: "10-01 14:45",
    },
    {
      id: "DEMO-R005",
      name: "绝对元运纪元",
      domain: "风水",
      state: "仅研究",
      level: "D",
      detail: "示意：未核纪元不能进入生产结论",
      secondary: "显式假设 · 示例约定",
      count: "1 条依据",
      updated: "09-30 11:05",
    },
    {
      id: "DEMO-R006",
      name: "六位卦结构",
      domain: "周易",
      state: "示例可执行",
      level: "C",
      detail: "示意：卦结构与错综互变",
      secondary: "自下而上 · 示例约定",
      count: "4 条依据",
      updated: "09-30 10:30",
    },
  ],
  evidence: [
    {
      id: "DEMO-E001",
      name: "六爻不動則不變，動則必變。",
      domain: "六爻",
      state: "已审选段",
      level: "C",
      detail: "静态展示摘录；标点整理，不作真实检索命中",
      secondary: "增删卜易 · 动变章",
      count: "动爻与变卦",
      updated: "10-02 09:12",
    },
    {
      id: "DEMO-E002",
      name: "乾為天「世」在六。",
      domain: "六爻",
      state: "已审选段",
      level: "C",
      detail: "静态展示的必要片段，不含整书正文",
      secondary: "增删卜易 · 世应章",
      count: "八宫世应定位",
      updated: "10-02 08:36",
    },
    {
      id: "DEMO-E003",
      name: "卦结构关系 · 示例片段",
      domain: "周易",
      state: "待复核",
      level: "C",
      detail: "仅为信息密度展示而设的占位记录",
      secondary: "周易 · 章节待定位",
      count: "六位卦结构",
      updated: "10-01 16:20",
    },
    {
      id: "DEMO-E004",
      name: "寄干取传 · 示例片段",
      domain: "六壬",
      state: "待复核",
      level: "C",
      detail: "仅为流派审核展示而设的占位记录",
      secondary: "六壬大全 · 九宗门",
      count: "四课取传次序",
      updated: "10-01 14:45",
    },
    {
      id: "DEMO-E005",
      name: "具名软件四化表 · 示例记录",
      domain: "紫微",
      state: "实现依据",
      level: "D",
      detail: "实现表不能包装成独立古典证据",
      secondary: "软件辅助 · 固定版本示意",
      count: "四化表约定",
      updated: "09-30 11:05",
    },
    {
      id: "DEMO-E006",
      name: "待核纪元 · 示例记录",
      domain: "风水",
      state: "仅研究",
      level: "D",
      detail: "只展示显式假设的边界，无实际原文",
      secondary: "研究假设 · 无已核原典",
      count: "绝对元运纪元",
      updated: "09-30 10:30",
    },
  ],
};
export const adminGroups = [
  {
    title: "工作台",
    items: [{ label: "仪表盘", icon: "grid", path: "/admin" }],
  },
  {
    title: "知识资产",
    items: [
      { label: "古籍管理", icon: "book", path: "/admin/classics" },
      { label: "章节管理", icon: "file", path: "/admin/chapters" },
      { label: "术语管理", icon: "file", path: "/admin/terms" },
      { label: "规则管理", icon: "layers", path: "/admin/rules" },
      { label: "Evidence 管理", icon: "shield", path: "/admin/evidence" },
    ],
  },
  {
    title: "审核与溯源",
    items: [
      { label: "来源管理", icon: "external", path: "/admin/sources" },
      {
        label: "RAW / Quarantine / Canonical",
        icon: "layers",
        path: "/admin/layers",
      },
      { label: "流派与冲突", icon: "layers", path: "/admin/conflicts" },
    ],
  },
  {
    title: "计算与解释",
    items: [
      { label: "算法与 Variant", icon: "settings", path: "/admin/algorithms" },
      {
        label: "AI Provider / Model",
        icon: "settings",
        path: "/admin/providers",
      },
      { label: "Prompt 版本", icon: "file", path: "/admin/prompts" },
      {
        label: "Eval / Golden Cases",
        icon: "check",
        path: "/admin/evaluations",
      },
      { label: "失败案例", icon: "file", path: "/admin/failures" },
    ],
  },
  {
    title: "系统",
    items: [
      { label: "用户与权限", icon: "shield", path: "/admin/users" },
      { label: "API / 系统日志", icon: "file", path: "/admin/logs" },
    ],
  },
];
