import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
C = ROOT / "data/canonical"

def load(path):
    return json.loads((C / path).read_text(encoding="utf-8"))

class DomainIntegrityTests(unittest.TestCase):
    def test_ten_wings(self):
        mins = {"xici_shang":2500,"xici_xia":2500,"shuogua":1000,"xugua":1000,"zagua":350}
        for name, minimum in mins.items():
            obj = load(f"yijing/ten_wings/{name}.json")
            text = obj["normalized_text"]
            self.assertGreaterEqual(len(text), minimum)
            self.assertNotIn("□", text)
            self.assertNotIn("�", text)
            self.assertEqual(obj["source_level"], "L0-public-domain-classic")

    def test_ziwei(self):
        z = load("ziwei/iztro_rules_v1.json")
        self.assertEqual(len(z["palaces"]), 12)
        self.assertEqual(len(z["major_stars"]), 14)
        self.assertEqual(len(z["four_transformations"]), 10)
        self.assertTrue(all(len(v)==4 for v in z["four_transformations"].values()))

    def test_qimen(self):
        q = load("qimen/qfdk_maoshan_v1.json")
        self.assertEqual(len(q["nine_palaces"]), 9)
        self.assertEqual(len(q["nine_stars"]), 9)
        self.assertEqual(len(q["eight_doors"]), 8)
        self.assertEqual(len(q["eight_deities"]), 8)
        self.assertEqual(len(q["solar_term_bureaus"]), 24)
        self.assertEqual(q["canonical_terms"]["san_qi"], ["乙","丙","丁"])
        self.assertEqual(q["canonical_terms"]["liu_yi"], ["戊","己","庚","辛","壬","癸"])

    def test_bibliographies(self):
        self.assertGreaterEqual(load("liuren/classics_catalog_v1.json")["record_count"], 120)
        self.assertGreaterEqual(load("taiyi/classics_catalog_v1.json")["record_count"], 90)

    def test_liuren_rules(self):
        x = load("liuren/rules_v1.json")
        self.assertEqual(len(x["month_general_by_solar_terms"]), 12)
        self.assertEqual(x["month_general_by_solar_terms"][0]["branch"], "亥")
        self.assertEqual(x["month_general_by_solar_terms"][-1]["branch"], "子")
        self.assertEqual(len(x["heavenly_generals"]["order"]), 12)
        self.assertEqual(
            x["three_transmissions"]["engine_selection_precedence"],
            ["贼克","比用","涉害","遥克","昴星","别责","八专","伏吟"],
        )
        self.assertEqual(len(x["branch_relations"]["clash"]), 12)
        self.assertEqual(x["branch_relations"]["clash"]["子"], "午")

    def test_taiyi_rules(self):
        x = load("taiyi/rules_v1.json")
        self.assertEqual(len(x["classical_methods"]), 4)
        self.assertEqual(len(x["taiyi_palace"]["yang_72"]), 72)
        self.assertEqual(len(x["taiyi_palace"]["yin_72"]), 72)
        self.assertEqual(set(x["taiyi_palace"]["valid_palace_numbers"]), {1,2,3,4,6,7,8,9})
        self.assertEqual(x["eight_doors"]["base_order"], ["开","休","生","伤","杜","景","死","惊"])
        self.assertEqual(len(x["sixteen_palaces"]), 16)
        self.assertEqual(x["luoshu_outer_order"], [8,3,4,9,2,7,6,1])
        self.assertTrue(all(v != 5 for v in x["taiyi_palace"]["yang_72"]))
        self.assertTrue(all(v != 5 for v in x["taiyi_palace"]["yin_72"]))

    def test_bazi_public_domain_classics(self):
        y = load("classics/bazi/yuanhai_ziping_v1.json")
        q = load("classics/bazi/qiongtong_baojian_v1.json")
        self.assertGreaterEqual(y["section_count"], 180)
        self.assertGreaterEqual(sum(len(x["text"]) for x in y["sections"]), 55000)
        self.assertEqual(y["cleaning"]["replacement_chars"], 0)
        self.assertTrue(any(x["title"] == "论大运" for x in y["sections"]))
        self.assertGreaterEqual(q["section_count"], 95)
        self.assertGreaterEqual(sum(len(x["text"]) for x in q["sections"]), 30000)
        self.assertEqual(q["cleaning"]["replacement_chars"], 0)
        self.assertTrue(any(x["title"] == "五行总论" for x in q["sections"]))
        self.assertTrue(any(x["title"] == "正月丙火" for x in q["sections"]))

    def test_tarot(self):
        t = load("tarot/rws_cn_v1.json")
        self.assertEqual(t["record_count"], 78)
        self.assertEqual(t["spread_count"], 9)
        self.assertEqual(t["counts"]["MajorArcana"], 22)
        self.assertEqual(t["counts"]["Swords"], 14)
        self.assertEqual(t["counts"]["Wands"], 14)
        self.assertEqual(t["counts"]["Cups"], 14)
        self.assertEqual(t["counts"]["Pentacles"], 14)
        self.assertTrue(all("pic" not in card for card in t["cards"]))

    def test_zeri_and_almanac(self):
        z = load("zeri/zeri_core_v1.json")
        a = load("almanac/scoring_v1.json")
        self.assertEqual(len(z["events"]), 10)
        self.assertEqual(len(z["branch_clashes"]), 12)
        self.assertEqual(len(z["sha_direction"]), 12)
        self.assertEqual(len(a["fixed_inauspicious"]["yang_gong_13_avoid"]), 13)
        self.assertEqual(len(a["fixed_inauspicious"]["san_niang_sha_lunar_days"]), 6)
        self.assertEqual(len(a["fixed_inauspicious"]["shi_e_da_bai_jiazi"]), 10)

    def test_fengshui(self):
        f = load("fengshui/calculation_v1.json")
        schools = load("fengshui/schools_v1.json")
        self.assertEqual(len(f["san_yuan_periods"]), 9)
        self.assertEqual(len(f["luoshu"]["palace_numbers"]), 9)
        self.assertEqual(len(f["luoshu"]["flight_path"]), 9)
        self.assertEqual(len(f["ming_gua"]["directions"]), 8)
        self.assertGreaterEqual(len(schools["schools"]), 7)
        self.assertIn("完整玄空宅盘", f["luoshu"]["limitation"])

    def test_fengshui_24_mountains(self):
        m = load("fengshui/twenty_four_mountains_v1.json")
        rows = m["records"]
        self.assertEqual(len(rows), 24)
        self.assertEqual(len({x["mountain"] for x in rows}), 24)
        self.assertEqual(len({x["compass_label"] for x in rows}), 24)
        self.assertEqual(rows[0]["mountain"], "子")
        self.assertEqual(rows[0]["compass_label"], "N2")
        self.assertEqual(rows[0]["start_degrees"], 352.5)
        self.assertEqual(rows[0]["end_degrees"], 7.5)
        self.assertTrue(rows[0]["wraps_zero"])
        self.assertEqual(rows[-1]["mountain"], "壬")
        for x in rows:
            self.assertEqual(x["center_degrees"], (x["index"] * 15) % 360)
            self.assertEqual(x["opposite"]["index"], (x["index"] + 12) % 24)

    def test_public_domain_bazi_classics(self):
        dit = load("classics/bazi/ditiansui_chanwei_v1.json")
        self.assertEqual(dit["section_count"], 63)
        self.assertGreaterEqual(sum(len(x["text"]) for x in dit["sections"]), 120000)
        self.assertEqual(dit["sections"][0]["title"], "通神论·一、天道")
        self.assertEqual(dit["sections"][-1]["title"], "六亲论·二十九、贞元")
        self.assertEqual(dit["cleaning"]["private_use_chars"], 0)
        text_map = json.loads(
            (ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_text_collation.json").read_text(encoding="utf-8")
        )
        self.assertEqual(text_map["summary"]["confirmed_corrections"], 164)
        self.assertEqual(text_map["summary"]["confirmed_replacements"], 164)
        self.assertEqual(text_map["summary"]["review_status"], "in_progress")
        text_corrections = {x["id"]: (x["old"], x["new"]) for x in text_map["corrections"]}
        self.assertEqual(text_corrections["ocr-017"][1], "无丑戌以刑冲之则库不开难得金印")
        self.assertEqual(text_corrections["ocr-018"][1], "印绶无亏享福全为官承荫有田园")
        self.assertEqual(text_corrections["ocr-020"][1], "显微阐幽尊彼往哲引伸触类")
        self.assertEqual(text_corrections["ocr-021"][1], "合刑者凶遇印者吉")
        self.assertEqual(text_corrections["ocr-022"][1], "身材琐小")
        self.assertTrue(next(x for x in text_map["corrections"] if x["id"] == "ocr-022").get("allow_existing_target"))
        self.assertEqual(text_corrections["ocr-023"][1], "逄煞㸔印及刃")
        self.assertEqual(text_corrections["ocr-024"][1], "经有云火明则㓕正谓此也")
        self.assertEqual(text_corrections["ocr-025"][1], "偏官有制作高命㸔巳申酉丑月官煞重叠")
        self.assertEqual(text_corrections["ocr-026"][1], "戊辰戊戌不为冲土得正位干守元㑹也")
        self.assertEqual(text_corrections["ocr-027"][1], "珞琭子云禄有三㑹又云得一分三")
        self.assertEqual(text_corrections["ocr-028"][1], "主老年䘮子日犯尅妻女命时逢一生不产")
        self.assertEqual(text_corrections["ocr-029"][1], "又云带辰午酉亥全中年䘮明又云自刑怕火")
        self.assertEqual(text_corrections["ocr-030"][1], "此十二位宫能回㓙作善乃曰天徳也")
        self.assertEqual(text_corrections["ocr-031"][1], "况犯者未必皆㐫若内有吉神相扶贵气相辅当为吉论")
        self.assertEqual(text_corrections["ocr-032"][1], "其日月会合之辰三合所照之方")
        self.assertEqual(text_corrections["ocr-033"][1], "故可回㓙作吉壶中子云")
        self.assertEqual(text_corrections["ocr-034"][1], "华盖为庇䕃清神主人旷逹神清")
        self.assertEqual(text_corrections["ocr-035"][1], "若人遇之主早承休䕃官序易陞")
        self.assertEqual(text_corrections["ocr-036"][1], "戊辰戊戌之土为魁罡相㑹乾坤厚徳")
        self.assertEqual(text_corrections["ocr-037"][1], "见寅虎则㑹起丙火而文章出焉")
        self.assertEqual(text_corrections["ocr-038"][1], "若重见禄位如甲日寅时又生正月财官俱弱只作建禄㸔若月日天元同")
        self.assertEqual(text_corrections["ocr-039"][1], "取虚露庚字亦主富贵全㸔月令何如")
        self.assertEqual(text_corrections["ocr-040"][1], "无亥卯以㑹之则形难变只作火土论")
        self.assertEqual(text_corrections["ocr-041"][1], "申宫水土长生之地入已午则逢火炼遂成剑㦸见子辰则逢水淬")
        self.assertEqual(text_corrections["ocr-042"][1], "伤官但能去官不能留煞必湏得羊刃合方成去官㽞煞")
        self.assertEqual(text_corrections["ocr-043"][1], "切不可见伤官格有官星便不作好命㸔又曰")
        self.assertEqual(text_corrections["ocr-044"][1], "财旺妻荣子更强柱中若要吞㗖煞管教金殿佐君王")
        self.assertEqual(text_corrections["ocr-045"][1], "煞乃尅我刃乃劫我命中之最㓙者肯言煞刃其知所重者欤")
        self.assertEqual(text_corrections["ocr-046"][1], "乙木捕䑕遇子多早歩蟾宫")
        self.assertEqual(text_corrections["ocr-047"][1], "冬子月忌三合水局水盛火㓕水火相停斯成旣济")
        self.assertEqual(text_corrections["ocr-048"][1], "官星喜财旺以生之印旺以䕶之故令其人能行仁布徳")
        self.assertEqual(text_corrections["ocr-049"][1], "后煞神得位嵗煞并临官化为鬼䘮身必矣")
        self.assertEqual(text_corrections["ocr-050"][1], "伤官得地贵禄遭伤䘮妻尅子剥职生灾")
        self.assertEqual(text_corrections["ocr-051"][1], "须观其气而消息之方可㫁也")
        self.assertEqual(text_corrections["ocr-052"][1], "亦不能埋劒㦸之金倘再兼行金水旺处")
        self.assertEqual(text_corrections["ocr-053"][1], "若申子辰全㑹起水局即成江海发波涛之声也")
        self.assertEqual(text_corrections["ocr-054"][1], "见己酉三合㑹起金局若人命生于丑月")
        self.assertEqual(text_corrections["ocr-055"][1], "兼起命宫㸔之落何宫分逐宫详断")
        self.assertEqual(text_corrections["ocr-056"][1], "五官㑹聚")
        self.assertEqual(text_corrections["ocr-057"][1], "更㸔喜忌何如不可执定")
        self.assertEqual(text_corrections["ocr-058"][1], "逢印㸔煞但有官煞在命行官煞乡亦作贵论")
        self.assertEqual(text_corrections["ocr-059"][1], "又㸔巳宫却被壊了酉中辛寅中丙方取")
        self.assertEqual(text_corrections["ocr-060"][1], "大凡亦㸔暗干与明干合气相干取用")
        self.assertEqual(text_corrections["ocr-061"][1], "又得木神䕶禄所以基本牢壮")
        self.assertEqual(text_corrections["ocr-062"][1], "又得金财以生之木印以䕶之所以基本牢壮")
        self.assertEqual(text_corrections["ocr-063"][1], "若无官事扰定主见重䘮此之谓欤")
        self.assertEqual(text_corrections["ocr-064"][1], "官符䘮吊白虎羊刃暴败天厄")
        self.assertEqual(text_corrections["ocr-065"][1], "金加子午多㐫暴若是丁人又喜逢")
        self.assertEqual(text_corrections["ocr-066"][1], "更㸔五行无土数定扶圣主掌陶镕")
        self.assertEqual(text_corrections["ocr-067"][1], "金加子午带死败故㓙甲子甲午之类是也")
        self.assertEqual(text_corrections["ocr-068"][1], "先强后弱必先吉而后㓙始弱终强亦始㓙而终吉")
        self.assertEqual(text_corrections["ocr-069"][1], "中遇㓙强岂可便作㓙兆")
        self.assertEqual(text_corrections["ocr-070"][1], "吉㓙悔吝可考而知")
        self.assertEqual(text_corrections["ocr-071"][1], "名曰造㣲岂云小补")
        self.assertEqual(text_corrections["ocr-072"][1], "人之八字全㸔用神")
        self.assertEqual(text_corrections["ocr-073"][1], "木得金裁㓜歳成名")
        self.assertEqual(text_corrections["ocr-074"][1], "㓜年失乳食神遭刑尅之宫")
        self.assertEqual(text_corrections["ocr-075"][1], "惟官印最宜相㑹德政加封")
        self.assertEqual(text_corrections["ocr-076"][1], "更㸔歳运何㓙何吉")
        self.assertEqual(text_corrections["ocr-077"][1], "七煞忌逢言䘮魄夀星欣遇曰还魂")
        self.assertEqual(text_corrections["ocr-078"][1], "财帛宫多母年早䘮若见官鬼出见母反长年")
        self.assertEqual(text_corrections["ocr-079"][1], "推寻子位先㸔妻宫死絶者嫡庻难存")
        self.assertEqual(text_corrections["ocr-080"][1], "月令虽强更㸔运神向背死絶刑伤鴈行失序")
        self.assertEqual(text_corrections["ocr-081"][1], "遭尅䧟则㓙祸不祥")
        self.assertEqual(text_corrections["ocr-082"][1], "五行会㓙曜为灾")
        self.assertEqual(text_corrections["ocr-083"][1], "五行无㓙煞侵犯名显声扬")
        self.assertEqual(text_corrections["ocr-084"][1], "伤官伤尽或见官星则㓙有十八格当从善恶推求")
        self.assertEqual(text_corrections["ocr-085"][1], "七煞官星各嫌覊绊填实则㓙忽然运到官乡")
        self.assertEqual(text_corrections["ocr-086"][1], "如临喜处以得祸是三合而隠㓙星或逢㓙处而返祥乃九宫而露吉曜")
        self.assertEqual(text_corrections["ocr-087"][1], "限守㓙神有根苗则不须畏惧")
        self.assertEqual(text_corrections["ocr-088"][1], "休囚者身性卑㣲旺相者名利壮寔")
        self.assertEqual(text_corrections["ocr-089"][1], "越外若贪必招㓙事噫甘贫养拙")
        self.assertEqual(text_corrections["ocr-090"][1], "葢人自生至老必从㣲以至少壮十嵗之时方当少年")
        self.assertEqual(text_corrections["ocr-091"][1], "欲交不交尚有㡬残之祸")
        self.assertEqual(text_corrections["ocr-092"][1], "吉运未到先作福㓙运过去始为殃")
        self.assertEqual(text_corrections["ocr-093"][1], "到死絶乡主骨肉死䘮自身衰祸钝闷百事蹇塞")
        self.assertEqual(text_corrections["ocr-094"][1], "有一字者㐫半二字俱无㓙莫能觧")
        self.assertEqual(text_corrections["ocr-095"][1], "巳酉之类谓之君臣庆㑹在两旬内")
        self.assertEqual(text_corrections["ocr-096"][1], "甲午见巳未之类谓之夫妻聚㑹")
        self.assertEqual(text_corrections["ocr-097"][1], "日月十二辰交㑹之所凡月之㑹朔日之璧于此位")
        self.assertEqual(text_corrections["ocr-098"][1], "谓之㑹劣谓之集十二月之辰")
        self.assertEqual(text_corrections["ocr-099"][1], "一嵗十二㑹太隂太阳隔液坎离之妙")
        self.assertEqual(text_corrections["ocr-100"][1], "此生万转图而放㑹合得可见也")
        self.assertEqual(text_corrections["ocr-101"][1], "故子与丑合得日月㑹同之数")
        self.assertEqual(text_corrections["ocr-102"][1], "所以在一旬内见方曰君臣庆㑹仍要别其阳为君")
        self.assertEqual(text_corrections["ocr-103"][1], "四冲生处自贫寒更值㓙神不足看")
        self.assertEqual(text_corrections["ocr-104"][1], "丁禄午见庚午截路空亡㐫壬午为徳合禄甲午为进神禄俱吉丙午喜神禄交羊刃半吉戊午伏羊刃禄多㐫")
        self.assertEqual(text_corrections["ocr-105"][1], "癸禄子见甲子进神禄主登科进达丙子交羊刃禄带福星贵有权戊子伏羊刃合贵禄半吉庚子印禄吉壬子正羊刃禄㐫")
        self.assertEqual(text_corrections["ocr-106"][1], "凡人命带禄或吉或㐫或贵或贱未可全靠便为吉论天乙妙㫖云")
        self.assertEqual(text_corrections["ocr-107"][1], "贵人嗔则㐫来可见命中有贵不可就为吉论要当细详")
        self.assertEqual(text_corrections["ocr-108"][1], "庚寅谓之破禄半吉半㓙壬寅谓之正禄带截路空亡必为僧道")
        self.assertEqual(text_corrections["ocr-109"][1], "乙禄卯见乙卯谓之喜神旺禄主吉丁卯为截路空亡主㐫己卯进神禄辛卯破禄又为交神半吉半㐫癸卯带太乙死禄虽贵终贫")
        self.assertEqual(text_corrections["ocr-110"][1], "丙禄己见己巳九天库禄主吉辛巳截路空亡癸巳伏贵神禄半吉半㐫乙巳旺马禄丁巳库禄俱吉")
        self.assertEqual(text_corrections["ocr-111"][1], "己禄午见庚午截路空亡壬午死鬼禄俱㐫甲午进神合禄显达之象丙午喜神禄戊午伏神羊刃禄㐫")
        self.assertEqual(text_corrections["ocr-112"][1], "庚禄申见壬申为大败禄甲申截路空亡禄俱㐫丙申大败禄多成败")
        self.assertEqual(text_corrections["ocr-113"][1], "辛禄酉见癸酉伏神禄水火相犯㐫乙酉破禄成败")
        self.assertEqual(text_corrections["ocr-114"][1], "八曰䭾屍十二驿马惟䭾屍最㓙见禄即屍")
        self.assertEqual(text_corrections["ocr-115"][1], "皆䭾屍也余旬凖此")
        self.assertEqual(text_corrections["ocr-116"][1], "乘轺则带职乘轩则三公䭾屍则得官即亡")
        self.assertEqual(text_corrections["ocr-117"][1], "如专羊刃主眼露性急㓙暴害物亲近恶党")
        self.assertEqual(text_corrections["ocr-118"][1], "亡神锦里一名儿女亡神岁去生他遇孤隔刼煞则㓙带禄贵则吉一重为妙又与日辰相统兼推吉㓙")
        self.assertEqual(text_corrections["ocr-119"][1], "㐫则昏浊邪侈毒害性重宿疾刑徒兵刀折伤")
        self.assertEqual(text_corrections["ocr-120"][1], "㓙则褊躁性窄顚诈狂妄浮荡是非酒色风流官府狱讼疽㾿气血气")
        self.assertEqual(text_corrections["ocr-121"][1], "其神最尊贵所至之处一切㓙煞隐然而避")
        self.assertEqual(text_corrections["ocr-122"][1], "夫徳者利物济人掩㓙作善之谓也")
        self.assertEqual(text_corrections["ocr-123"][1], "贵神在位诸煞伏藏二徳扶持众㓙解散凡命中带㓙煞得此二徳扶化㓙不为甚须要日上见时上不犯尅冲刑破方吉凡人得之一生安逸不犯刑不逢盗纵遇㓙祸自然消散")
        self.assertEqual(text_corrections["ocr-124"][1], "更有月徳并者尤好纵有㓙煞亦主清显")
        self.assertEqual(text_corrections["ocr-125"][1], '午己未气过阳宫重离相㑹炳灵交光发辉炎上乃曰')
        self.assertEqual(text_corrections["ocr-126"][1], '华葢悬针破字】\n 壬申金【戈㦸大喜子午卯酉平头大败')
        self.assertEqual(text_corrections["ocr-127"][1], '荧煌寒林缀叶之光隔幔㸃衣之彩方朔以萤火名之')
        self.assertEqual(text_corrections["ocr-128"][1], '相资主贵大林有风杨柳㑹火二木最忌桑柘癸丑为')
        self.assertEqual(text_corrections["ocr-129"][1], '命爱申年亥时乃地天交㤗\n 已为大驿大驿者人烟凑')
        self.assertEqual(text_corrections["ocr-130"][1], '未乃木库如人筑墙垣以䕶百花也以百花言未中有')
        self.assertEqual(text_corrections["ocr-131"][1], '也其禽蛇子亦水也其禽䑕午亦火也其禽马水胜火故豕食蛇火为水所害故马食䑕屎而腹胀然亦有不相胜者午马也子䑕也酉鸡也卯兔也水胜火䑕何不逐马金胜木鸡何不啄兔亥豕也未羊也丑牛也土胜水牛羊何不杀豕巳蛇也申猴也火胜金蛇何不食猕猴猕猴畏防者也囓猕猴者犬也防水猕猴金也水不胜金猕猴何故畏䑕戌土也申猴也土不胜金')
        self.assertEqual(text_corrections["ocr-132"][1], '如人生后三日以沐浴之㡬至困絶也六曰冠带万物')
        self.assertEqual(text_corrections["ocr-133"][1], '得位本胜于主者多得祖䕃主胜于本者当自卓立本主两强富贵双全四柱中更抑扬归中无太过不及方作好命有一位不及必主蹇滞然诸家命术皆云好年不如好月好月不如好日好日不如好时大率以年则统乎一嵗月则该乎三十而时日为得之独不知得日时之吉而月不应反为无用况用神多取诸月是月又可轻乎唐李虚中独以日干为主却以年月时合㸔生尅制化旺相休囚取立')
        self.assertEqual(text_corrections["ocr-134"][1], '发福于生时日者三阳之㑹帝皇之象时者近侍之臣')
        self.assertEqual(text_corrections["ocr-135"][1], '运尅嵗与日犯同主破耗䘮事有贵人禄马觧之稍吉')
        self.assertEqual(text_corrections["ocr-136"][1], '嫉妬相害故酉人见戍则㓙戍人见酉无灾若乙酉人')
        self.assertEqual(text_corrections["ocr-137"][1], '鬼在己上为害以三合相㑹在辰则减福以六合相亲')
        self.assertEqual(text_corrections["ocr-138"][1], '下生人月日时支干得御䇿全并尅身者定贵马前一辰为御后一辰为䇿假令甲子金命正月辛丑日卯时生以子人马在寅逢禄又本命子与生日丑在马后为䇿卯时在马前为御又马是')
        self.assertEqual(text_corrections["ocr-139"][1], '爱子午相冲为飞马见鞭䇿入格主贵\n 有驿马清浊甲子得丙寅禄马同乡又丙为食神乘长生马丁丑得丁亥为天乙天官乘临官马若乘长生临官马或带食禄贵气则遇一当百若乘病絶空亡马更値破败交退伏神则遇而不遇纵为官粗浊卑贱非清要之职\n 又曰凡看驿马有四专名位生旺病絶駞宝啣花及倒食互换不同中间好恶荣辱须于岁运鞭䇿细详之四专者如申子辰')
        self.assertEqual(text_corrections["ocr-140"][1], '在申冲动寅即太岁为鞭䇿小运在申即小运为鞭䇿多主动更看申与寅互换')
        self.assertEqual(text_corrections["ocr-141"][1], '分优劣即前六十甲子吉㓙其归要与禄马同窠不犯')
        self.assertEqual(text_corrections["ocr-142"][1], '勲业超羣带天月二徳者㓙灾不犯带六仪者才智出')
        self.assertEqual(text_corrections["ocr-143"][1], '恶死若旌钺更与三公煞㑹同一位主殊贵今之谈命')
        self.assertEqual(text_corrections["ocr-144"][1], '命无福神往还名带煞主㓙\n 有临空印乃印落空亡支无六合见官贵至贱而无成也\n 有自刑印如庚戌人带乙丑金人见金印固好丑戌相刑以金刑金此类不如无虽有少福亦终贱余准此推\n 凡论印更得眞五行与纳音同气尤妙但主少安逸不利六亲难为子息\n 论徳秀\n 夫徳者本月生旺之徳秀者合天地中和之气五行变化而成者也又曰徳者阴阳解㐫之神秀者天地清秀之气')
        self.assertEqual(text_corrections["ocr-145"][1], '于三合细推排天盘加得㐫星到命似风灯不久摧水')
        self.assertEqual(text_corrections["ocr-146"][1], '居此地贫穷蹇滞过平生㓙星恶曜如临到大限浑如')
        self.assertEqual(text_corrections["ocr-147"][1], '则为福已极则将反而为㓙极盛之地十干中正处是')
        self.assertEqual(text_corrections["ocr-148"][1], '未甲辰乙卯壬子癸丑皆㓙象也金紧木慢女命犯之定尅夫害子不贞洁理愚歌云倒悬羊刃又同行形骸不免塡沟壑又云飞刃倒戈终见乖小人得此便为灾空亡截路同相见此身安得出尘埃又云羊刃更兼倒戈必作无头之鬼是羊刃带诸恶煞尤㓙\n 凡人行运最怕羊刃主作')
        self.assertEqual(text_corrections["ocr-149"][1], '生破散与咸池六害并多㐫暴卒惟夹贵华盖三竒学')
        self.assertEqual(text_corrections["ocr-150"][1], '两号天中见合长生旺不㓙加临冲尅兼刑禄官职陞')
        self.assertEqual(text_corrections["ocr-151"][1], '正余干午未半之所以为㐫者当气冲之地左鼓则风煞在右右鼓则风煞在左故阴阳男女取冲前冲后不同若岁运临之如物当风动摇顚倒不得宁息不有内疾必有外难虽富贵崇高势位炎盛大运逢之十年可畏立朝定当窜逐居家必罹㓙咎纵有吉神扶持不免祸福倚伏尤忌先吉后㓙临旺之后欲出未出之际㓙祸尤的生命逢之主形骸')
        self.assertEqual(text_corrections["ocr-152"][1], '贱格再値一切防神则愈㓙又曰金生处主大风瘫痪')
        self.assertEqual(text_corrections["ocr-153"][1], '杖刃土坠落瘟疫尅身大㓙若有福神相助多是武权亦如刼煞之类要见官星印绶生旺处为佳神白经云灾煞畏乎尅生处却为祥正谓此也\n 论六厄\n 厄者遭乎难者也常居马前一辰刼后二辰死而不生谓之厄申子辰水局水死在卯寅午戌火局火死在酉亥卯未木局木死在午巳酉丑金局金死在子所以为厄若有救䕶有扶持逢生旺兼贵气相')
        self.assertEqual(text_corrections["ocr-154"][1], '此煞大忌金神白虎并则㓙牛马犬畜等伤亦是不独虎狼也不尅身与福同宫者不用大抵此煞凡命遇之身若尅煞多心路计巧主掌刑法之任或为将帅专行诛戮煞若尅身主非命而终小人逢之非横灾祸行年至此亦主口舌刑狱等事又云値两位全者灾重一位者轻又云有鬼则灾重无鬼则灾轻\n 论孤辰寡宿【及隔角煞】\n 先贤有云老而无夫曰寡㓜而无父曰孤此其义也辰')
        self.assertEqual(text_corrections["ocr-155"][1], '亲不聚财多生女更带诸㓙煞主不令终珞琭子云凭')
        self.assertEqual(text_corrections["ocr-156"][1], '交战大败无一生还喻极㐫也六甲旬中十个日値禄')
        self.assertEqual(text_corrections["ocr-157"][1], '更有天中官符大耗者定㓙\n 水溺煞 此煞取丙子癸未癸丑上带咸池金刃羊刃盖丙子纳音水又子为水旺之地未为井宿之居丑为三河之分更纳音尅身决不可免古歌云刼煞尅身名顚坠金神羊刃防同位要知自缢最㓙神戌巳辰亥并寅未子酉一例为㓙煞卯申丑未依前是大忌空亡兼墓鬼官符大耗仍须避丙子癸未并癸丑咸池金煞羊刃畏五行更若来尅身一死悬梁一溺水\n 挂劒煞 此煞取己酉丑申四柱纯全者是或重带已酉丑亦是更犯官符元辰白虎金神等类五行刑尅本命者主㓙暴杀人或反为人所杀诗')
        self.assertEqual(text_corrections["ocr-158"][1], '刃的煞飞廉等会命限必㓙主堕于天眞雷伤虎啗天')
        self.assertEqual(text_corrections["ocr-159"][1], '月时日犯之无贵神解救㓙恶短折\n 丧吊煞 一名横关煞取命前二辰为丧门命后二辰为吊客其或太岁㐫煞并临大小运限必主祸古诗云五官六死十二病三丧十一吊来临可见此十二宫一太岁歌不惟命犯不吉流年尤㓙若月有羊刃来佐㐫煞临时则横关也古歌云横关恶煞少人知月禄㓙神又及时纵有吉星重疉')
        self.assertEqual(text_corrections["ocr-160"][1], '旺干加临日时带两重者㓙更与悬针相见主决配伤残\n 浮沉煞【血刃同】从戌上起子逆行至本生年住却从年宫数看在何宫只在财帛宫名串钱主富蓄余皆㓙甲乙己庚壬人犯之稍轻')
        self.assertEqual(text_corrections["ocr-161"][1], '之\n 以上诸煞凡言尅身谓㓙煞下纳音尅生年太岁纳')
        self.assertEqual(text_corrections["ocr-162"][1], '令得旺气忌有败之者凡㓙神欲令得衰气忌有助之者又云相冲相破三合六合命中有之即求五行相得何如或祸中生福福中生祸如死絶复生空亡受破相尅相成则祸中生福反此则福中生祸命书云道途贱吏岂无驿马攀鞍市井博徒亦有三奇夹贵子平云君子格中也犯七煞阳刃小人命内亦有正印官星由是观之吉㓙神煞不可拘定轻重较量要在通变大抵㐫煞所居于神不宜带真鬼')
        self.assertEqual(text_corrections["ocr-163"][1], '坐支兼得月时及行运吉㓙\n 甲乙\n 甲木属阳乃栋梁之')
        self.assertEqual(text_corrections["ocr-164"][1], '鬼论分身鬼强弱定其吉㐫寿夭若制伏得中作偏官论太过反不为福更㸔日干于所生月内有力无')
        self.assertFalse(text_map["summary"]["canonical_ready"])
        corrections = {(x["old"], x["new"]) for x in text_map["corrections"]}
        self.assertIn(("若失时防局卽韬光", "若失时䘮局卽韬光"), corrections)
        self.assertIn(("虽防𦕈之金亦不能制", "虽㣲𦕈之金亦不能制"), corrections)
        self.assertIn(("火强燥而防𦕈水既济以寛和", "火强燥而㣲𦕈水既济以寛和"), corrections)
        self.assertIn(("金水相停防合含光圆融皎洁", "金水相停㑹合含光圆融皎洁"), corrections)
        self.assertIn(("临老蛉仃者裔苦根甘", "临老伶仃者裔苦根甘"), corrections)
        self.assertIn(("阳刄者天上之防星人间之恶煞", "阳刄者天上之凶星人间之恶煞"), corrections)
        self.assertIn(("年干父兮支母日干巳兮支妻", "年干父兮支母日干己兮支妻"), corrections)
        self.assertIn(("飞防名天瞽支干无气主无目", "飞廉名天瞽支干无气主无目"), corrections)
        self.assertIn(("诸神之领防其説有二", "诸神之领袖其説有二"), corrections)
        self.assertIn(("大运虽防其小运却吉", "大运虽凶其小运却吉"), corrections)
        self.assertIn(("此小运又名行年不可不防醉醒", "此小运又名行年不可不究醉醒"), corrections)
        self.assertIn(("身旺官防财名寡合", "身旺官微财名寡合"), corrections)
        self.assertIn(("身坐比肩成比局当为防度新郎", "身坐比肩成比局当为几度新郎"), corrections)
        self.assertIn(("癸水相防为辛苦之经商", "癸水相会为辛苦之经商"), corrections)
        self.assertIn(("九宫防溺怕防运又怕防年", "九宫陷溺怕凶运又怕凶年"), corrections)
        self.assertIn(("或以申亥包酉戌防系天干何物", "或以申亥包酉戌看系天干何物"), corrections)
        self.assertFalse((C / "classics/bazi/sanming_tonghui_v1.json").exists())

    def test_sanming_pua_collation_progress(self):
        audit_path = ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_pua_audit.json"
        map_path = ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_pua_collation.json"
        audit = json.loads(audit_path.read_text(encoding="utf-8"))
        mapping = json.loads(map_path.read_text(encoding="utf-8"))
        summary = mapping["summary"]
        self.assertEqual(audit["total_private_use_chars"], 524)
        self.assertEqual(audit["unique_private_use_chars"], 86)
        self.assertEqual(summary["confirmed_mappings"], 86)
        self.assertEqual(summary["confirmed_occurrences"], 524)
        self.assertEqual(summary["remaining_unique_codepoints"], 0)
        self.assertEqual(summary["remaining_occurrences"], 0)
        self.assertTrue(all(x["status"] == "confirmed" for x in mapping["mappings"]))
        self.assertIn(("U+E4BF", "琐"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA40", "𠒋"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E749", "渺"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECDE", "点"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED3F", "眩"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7B", "冢"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA85", "刑"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EB8E", "弦"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE60", "蒙"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA23", "胤"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED92", "算"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA1", "过"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E898", "瓜"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA6", "蓬"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA5B", "传"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA62", "备"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E8AA", "恶"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA26", "兮"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E9C7", "真"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAC0", "嗤"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAE6", "涂"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAF6", "压"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECD6", "熬"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7C", "寵"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEB8", "𫑗"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E59C", "燥"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBB8", "博"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBDE", "哲"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EDE6", "苑"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E3E5", "坷"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECEC", "管"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E10C", "𣷉"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E5AB", "𨽻"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED9E", "簪"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE26", "亏"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE6D", "博"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6A", "惕"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6C", "场"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBA5", "忘"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECCA", "烽"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED51", "瞽"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA3", "递"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EED7", "开"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEE4", "徒"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEE5", "隐"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6B", "疡"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7D", "凌"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAA7", "段"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBC2", "惨"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED94", "算"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF17", "鬓"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF33", "类"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF3F", "抟"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF67", "参"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E5E0", "𦕈"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA9F", "𭅺"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E87D", "曄"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E9FC", "𡎊"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA3F", "充"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA53", "含"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBDB", "𢫎"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECA6", "激"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE9C", "逄"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E37B", "𤥣"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E7E9", "崙"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBC1", "𢡟"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECC7", "𤇍"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        contextual = mapping["contextual_mappings"]
        self.assertEqual(len(contextual), 1)
        self.assertEqual(contextual[0]["codepoint"], "U+E7E8")
        self.assertEqual(contextual[0]["count"], 5)
        self.assertEqual(sum(x["count"] for x in contextual[0]["replacements"]), 5)
        self.assertIn(("韩命书", "韩𭹱命书"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("又恐天年多", "又恐天年多摩罗"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("为人巧虚诈", "为人惯巧虚诈"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("临老蛉者裔苦根甘", "临老蛉仃者裔苦根甘"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        singleton = next(x for x in mapping["mappings"] if x["codepoint"] == "U+EA62")
        self.assertEqual(singleton["count"], 1)
        self.assertEqual(len(singleton["source_anchors"]), 1)
        self.assertGreaterEqual(len(singleton["evidence"]), 2)
        self.assertFalse((C / "classics/bazi/sanming_tonghui_v1.json").exists())

    def test_hetu_luoshu(self):
        h = load("foundations/hetu_luoshu_v1.json")
        pairs = h["hetu"]["pairs"]
        self.assertEqual(len(pairs), 5)
        self.assertTrue(all(x["completing"] - x["generating"] == 5 for x in pairs))
        matrix = h["luoshu"]["matrix_south_up"]
        self.assertEqual(matrix, [[4,9,2],[3,5,7],[8,1,6]])
        rows = matrix
        cols = [list(x) for x in zip(*matrix)]
        diags = [[matrix[i][i] for i in range(3)], [matrix[i][2-i] for i in range(3)]]
        self.assertTrue(all(sum(line) == 15 for line in rows + cols + diags))
        self.assertEqual(len(h["luoshu"]["nine_palaces"]), 9)
        self.assertEqual(h["hetu"]["textual_attribution_status"], "UNVERIFIED")

if __name__ == "__main__":
    unittest.main()
