import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
C = ROOT / "data/canonical"

def load(path):
    return json.loads((C / path).read_text(encoding="utf-8"))

class DomainIntegrityTests(unittest.TestCase):
    def test_ten_wings(self):
        mins = {"xici_shang":2500,"xici_xia":2500,"shuogua":1000,"xugua":1000,"zagua":350}
        for name, minimum in mins.items():
            obj = load(f"yijing/ten_wings/{name}.json")
            text = obj["normalized_text"]
            self.assertGreaterEqual(len(text), minimum)
            self.assertNotIn("□", text)
            self.assertNotIn("�", text)
            self.assertEqual(obj["source_level"], "L0-public-domain-classic")

    def test_ziwei(self):
        z = load("ziwei/iztro_rules_v1.json")
        self.assertEqual(len(z["palaces"]), 12)
        self.assertEqual(len(z["major_stars"]), 14)
        self.assertEqual(len(z["four_transformations"]), 10)
        self.assertTrue(all(len(v)==4 for v in z["four_transformations"].values()))

    def test_qimen(self):
        q = load("qimen/qfdk_maoshan_v1.json")
        self.assertEqual(len(q["nine_palaces"]), 9)
        self.assertEqual(len(q["nine_stars"]), 9)
        self.assertEqual(len(q["eight_doors"]), 8)
        self.assertEqual(len(q["eight_deities"]), 8)
        self.assertEqual(len(q["solar_term_bureaus"]), 24)
        self.assertEqual(q["canonical_terms"]["san_qi"], ["乙","丙","丁"])
        self.assertEqual(q["canonical_terms"]["liu_yi"], ["戊","己","庚","辛","壬","癸"])

    def test_bibliographies(self):
        self.assertGreaterEqual(load("liuren/classics_catalog_v1.json")["record_count"], 120)
        self.assertGreaterEqual(load("taiyi/classics_catalog_v1.json")["record_count"], 90)

    def test_liuren_rules(self):
        x = load("liuren/rules_v1.json")
        self.assertEqual(len(x["month_general_by_solar_terms"]), 12)
        self.assertEqual(x["month_general_by_solar_terms"][0]["branch"], "亥")
        self.assertEqual(x["month_general_by_solar_terms"][-1]["branch"], "子")
        self.assertEqual(len(x["heavenly_generals"]["order"]), 12)
        self.assertEqual(
            x["three_transmissions"]["engine_selection_precedence"],
            ["贼克","比用","涉害","遥克","昴星","别责","八专","伏吟"],
        )
        self.assertEqual(len(x["branch_relations"]["clash"]), 12)
        self.assertEqual(x["branch_relations"]["clash"]["子"], "午")

    def test_taiyi_rules(self):
        x = load("taiyi/rules_v1.json")
        self.assertEqual(len(x["classical_methods"]), 4)
        self.assertEqual(len(x["taiyi_palace"]["yang_72"]), 72)
        self.assertEqual(len(x["taiyi_palace"]["yin_72"]), 72)
        self.assertEqual(set(x["taiyi_palace"]["valid_palace_numbers"]), {1,2,3,4,6,7,8,9})
        self.assertEqual(x["eight_doors"]["base_order"], ["开","休","生","伤","杜","景","死","惊"])
        self.assertEqual(len(x["sixteen_palaces"]), 16)
        self.assertEqual(x["luoshu_outer_order"], [8,3,4,9,2,7,6,1])
        self.assertTrue(all(v != 5 for v in x["taiyi_palace"]["yang_72"]))
        self.assertTrue(all(v != 5 for v in x["taiyi_palace"]["yin_72"]))

    def test_bazi_public_domain_classics(self):
        y = load("classics/bazi/yuanhai_ziping_v1.json")
        q = load("classics/bazi/qiongtong_baojian_v1.json")
        self.assertGreaterEqual(y["section_count"], 180)
        self.assertGreaterEqual(sum(len(x["text"]) for x in y["sections"]), 55000)
        self.assertEqual(y["cleaning"]["replacement_chars"], 0)
        self.assertTrue(any(x["title"] == "论大运" for x in y["sections"]))
        self.assertGreaterEqual(q["section_count"], 95)
        self.assertGreaterEqual(sum(len(x["text"]) for x in q["sections"]), 30000)
        self.assertEqual(q["cleaning"]["replacement_chars"], 0)
        self.assertTrue(any(x["title"] == "五行总论" for x in q["sections"]))
        self.assertTrue(any(x["title"] == "正月丙火" for x in q["sections"]))

    def test_tarot(self):
        t = load("tarot/rws_cn_v1.json")
        self.assertEqual(t["record_count"], 78)
        self.assertEqual(t["spread_count"], 9)
        self.assertEqual(t["counts"]["MajorArcana"], 22)
        self.assertEqual(t["counts"]["Swords"], 14)
        self.assertEqual(t["counts"]["Wands"], 14)
        self.assertEqual(t["counts"]["Cups"], 14)
        self.assertEqual(t["counts"]["Pentacles"], 14)
        self.assertTrue(all("pic" not in card for card in t["cards"]))

    def test_zeri_and_almanac(self):
        z = load("zeri/zeri_core_v1.json")
        a = load("almanac/scoring_v1.json")
        self.assertEqual(len(z["events"]), 10)
        self.assertEqual(len(z["branch_clashes"]), 12)
        self.assertEqual(len(z["sha_direction"]), 12)
        self.assertEqual(len(a["fixed_inauspicious"]["yang_gong_13_avoid"]), 13)
        self.assertEqual(len(a["fixed_inauspicious"]["san_niang_sha_lunar_days"]), 6)
        self.assertEqual(len(a["fixed_inauspicious"]["shi_e_da_bai_jiazi"]), 10)

    def test_fengshui(self):
        f = load("fengshui/calculation_v1.json")
        schools = load("fengshui/schools_v1.json")
        self.assertEqual(len(f["san_yuan_periods"]), 9)
        self.assertEqual(len(f["luoshu"]["palace_numbers"]), 9)
        self.assertEqual(len(f["luoshu"]["flight_path"]), 9)
        self.assertEqual(len(f["ming_gua"]["directions"]), 8)
        self.assertGreaterEqual(len(schools["schools"]), 7)
        self.assertIn("完整玄空宅盘", f["luoshu"]["limitation"])

    def test_fengshui_24_mountains(self):
        m = load("fengshui/twenty_four_mountains_v1.json")
        rows = m["records"]
        self.assertEqual(len(rows), 24)
        self.assertEqual(len({x["mountain"] for x in rows}), 24)
        self.assertEqual(len({x["compass_label"] for x in rows}), 24)
        self.assertEqual(rows[0]["mountain"], "子")
        self.assertEqual(rows[0]["compass_label"], "N2")
        self.assertEqual(rows[0]["start_degrees"], 352.5)
        self.assertEqual(rows[0]["end_degrees"], 7.5)
        self.assertTrue(rows[0]["wraps_zero"])
        self.assertEqual(rows[-1]["mountain"], "壬")
        for x in rows:
            self.assertEqual(x["center_degrees"], (x["index"] * 15) % 360)
            self.assertEqual(x["opposite"]["index"], (x["index"] + 12) % 24)

    def test_public_domain_bazi_classics(self):
        dit = load("classics/bazi/ditiansui_chanwei_v1.json")
        self.assertEqual(dit["section_count"], 63)
        self.assertGreaterEqual(sum(len(x["text"]) for x in dit["sections"]), 120000)
        self.assertEqual(dit["sections"][0]["title"], "通神论·一、天道")
        self.assertEqual(dit["sections"][-1]["title"], "六亲论·二十九、贞元")
        self.assertEqual(dit["cleaning"]["private_use_chars"], 0)
        text_map = json.loads(
            (ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_text_collation.json").read_text(encoding="utf-8")
        )
        self.assertEqual(text_map["summary"]["confirmed_corrections"], 384)
        self.assertEqual(text_map["summary"]["confirmed_replacements"], 384)
        self.assertEqual(text_map["summary"]["review_status"], "in_progress")
        text_corrections = {x["id"]: (x["old"], x["new"]) for x in text_map["corrections"]}
        self.assertEqual(text_corrections["ocr-017"][1], "无丑戌以刑冲之则库不开难得金印")
        self.assertEqual(text_corrections["ocr-018"][1], "印绶无亏享福全为官承荫有田园")
        self.assertEqual(text_corrections["ocr-020"][1], "显微阐幽尊彼往哲引伸触类")
        self.assertEqual(text_corrections["ocr-021"][1], "合刑者凶遇印者吉")
        self.assertEqual(text_corrections["ocr-022"][1], "身材琐小")
        self.assertTrue(next(x for x in text_map["corrections"] if x["id"] == "ocr-022").get("allow_existing_target"))
        self.assertEqual(text_corrections["ocr-023"][1], "逄煞㸔印及刃")
        self.assertEqual(text_corrections["ocr-024"][1], "经有云火明则㓕正谓此也")
        self.assertEqual(text_corrections["ocr-025"][1], "偏官有制作高命㸔巳申酉丑月官煞重叠")
        self.assertEqual(text_corrections["ocr-026"][1], "戊辰戊戌不为冲土得正位干守元㑹也")
        self.assertEqual(text_corrections["ocr-027"][1], "珞琭子云禄有三㑹又云得一分三")
        self.assertEqual(text_corrections["ocr-028"][1], "主老年䘮子日犯尅妻女命时逢一生不产")
        self.assertEqual(text_corrections["ocr-029"][1], "又云带辰午酉亥全中年䘮明又云自刑怕火")
        self.assertEqual(text_corrections["ocr-030"][1], "此十二位宫能回㓙作善乃曰天徳也")
        self.assertEqual(text_corrections["ocr-031"][1], "况犯者未必皆㐫若内有吉神相扶贵气相辅当为吉论")
        self.assertEqual(text_corrections["ocr-032"][1], "其日月会合之辰三合所照之方")
        self.assertEqual(text_corrections["ocr-033"][1], "故可回㓙作吉壶中子云")
        self.assertEqual(text_corrections["ocr-034"][1], "华盖为庇䕃清神主人旷逹神清")
        self.assertEqual(text_corrections["ocr-035"][1], "若人遇之主早承休䕃官序易陞")
        self.assertEqual(text_corrections["ocr-036"][1], "戊辰戊戌之土为魁罡相㑹乾坤厚徳")
        self.assertEqual(text_corrections["ocr-037"][1], "见寅虎则㑹起丙火而文章出焉")
        self.assertEqual(text_corrections["ocr-038"][1], "若重见禄位如甲日寅时又生正月财官俱弱只作建禄㸔若月日天元同")
        self.assertEqual(text_corrections["ocr-039"][1], "取虚露庚字亦主富贵全㸔月令何如")
        self.assertEqual(text_corrections["ocr-040"][1], "无亥卯以㑹之则形难变只作火土论")
        self.assertEqual(text_corrections["ocr-041"][1], "申宫水土长生之地入已午则逢火炼遂成剑㦸见子辰则逢水淬")
        self.assertEqual(text_corrections["ocr-042"][1], "伤官但能去官不能留煞必湏得羊刃合方成去官㽞煞")
        self.assertEqual(text_corrections["ocr-043"][1], "切不可见伤官格有官星便不作好命㸔又曰")
        self.assertEqual(text_corrections["ocr-044"][1], "财旺妻荣子更强柱中若要吞㗖煞管教金殿佐君王")
        self.assertEqual(text_corrections["ocr-045"][1], "煞乃尅我刃乃劫我命中之最㓙者肯言煞刃其知所重者欤")
        self.assertEqual(text_corrections["ocr-046"][1], "乙木捕䑕遇子多早歩蟾宫")
        self.assertEqual(text_corrections["ocr-047"][1], "冬子月忌三合水局水盛火㓕水火相停斯成旣济")
        self.assertEqual(text_corrections["ocr-048"][1], "官星喜财旺以生之印旺以䕶之故令其人能行仁布徳")
        self.assertEqual(text_corrections["ocr-049"][1], "后煞神得位嵗煞并临官化为鬼䘮身必矣")
        self.assertEqual(text_corrections["ocr-050"][1], "伤官得地贵禄遭伤䘮妻尅子剥职生灾")
        self.assertEqual(text_corrections["ocr-051"][1], "须观其气而消息之方可㫁也")
        self.assertEqual(text_corrections["ocr-052"][1], "亦不能埋劒㦸之金倘再兼行金水旺处")
        self.assertEqual(text_corrections["ocr-053"][1], "若申子辰全㑹起水局即成江海发波涛之声也")
        self.assertEqual(text_corrections["ocr-054"][1], "见己酉三合㑹起金局若人命生于丑月")
        self.assertEqual(text_corrections["ocr-055"][1], "兼起命宫㸔之落何宫分逐宫详断")
        self.assertEqual(text_corrections["ocr-056"][1], "五官㑹聚")
        self.assertEqual(text_corrections["ocr-057"][1], "更㸔喜忌何如不可执定")
        self.assertEqual(text_corrections["ocr-058"][1], "逢印㸔煞但有官煞在命行官煞乡亦作贵论")
        self.assertEqual(text_corrections["ocr-059"][1], "又㸔巳宫却被壊了酉中辛寅中丙方取")
        self.assertEqual(text_corrections["ocr-060"][1], "大凡亦㸔暗干与明干合气相干取用")
        self.assertEqual(text_corrections["ocr-061"][1], "又得木神䕶禄所以基本牢壮")
        self.assertEqual(text_corrections["ocr-062"][1], "又得金财以生之木印以䕶之所以基本牢壮")
        self.assertEqual(text_corrections["ocr-063"][1], "若无官事扰定主见重䘮此之谓欤")
        self.assertEqual(text_corrections["ocr-064"][1], "官符䘮吊白虎羊刃暴败天厄")
        self.assertEqual(text_corrections["ocr-065"][1], "金加子午多㐫暴若是丁人又喜逢")
        self.assertEqual(text_corrections["ocr-066"][1], "更㸔五行无土数定扶圣主掌陶镕")
        self.assertEqual(text_corrections["ocr-067"][1], "金加子午带死败故㓙甲子甲午之类是也")
        self.assertEqual(text_corrections["ocr-068"][1], "先强后弱必先吉而后㓙始弱终强亦始㓙而终吉")
        self.assertEqual(text_corrections["ocr-069"][1], "中遇㓙强岂可便作㓙兆")
        self.assertEqual(text_corrections["ocr-070"][1], "吉㓙悔吝可考而知")
        self.assertEqual(text_corrections["ocr-071"][1], "名曰造㣲岂云小补")
        self.assertEqual(text_corrections["ocr-072"][1], "人之八字全㸔用神")
        self.assertEqual(text_corrections["ocr-073"][1], "木得金裁㓜歳成名")
        self.assertEqual(text_corrections["ocr-074"][1], "㓜年失乳食神遭刑尅之宫")
        self.assertEqual(text_corrections["ocr-075"][1], "惟官印最宜相㑹德政加封")
        self.assertEqual(text_corrections["ocr-076"][1], "更㸔歳运何㓙何吉")
        self.assertEqual(text_corrections["ocr-077"][1], "七煞忌逢言䘮魄夀星欣遇曰还魂")
        self.assertEqual(text_corrections["ocr-078"][1], "财帛宫多母年早䘮若见官鬼出见母反长年")
        self.assertEqual(text_corrections["ocr-079"][1], "推寻子位先㸔妻宫死絶者嫡庻难存")
        self.assertEqual(text_corrections["ocr-080"][1], "月令虽强更㸔运神向背死絶刑伤鴈行失序")
        self.assertEqual(text_corrections["ocr-081"][1], "遭尅䧟则㓙祸不祥")
        self.assertEqual(text_corrections["ocr-082"][1], "五行会㓙曜为灾")
        self.assertEqual(text_corrections["ocr-083"][1], "五行无㓙煞侵犯名显声扬")
        self.assertEqual(text_corrections["ocr-084"][1], "伤官伤尽或见官星则㓙有十八格当从善恶推求")
        self.assertEqual(text_corrections["ocr-085"][1], "七煞官星各嫌覊绊填实则㓙忽然运到官乡")
        self.assertEqual(text_corrections["ocr-086"][1], "如临喜处以得祸是三合而隠㓙星或逢㓙处而返祥乃九宫而露吉曜")
        self.assertEqual(text_corrections["ocr-087"][1], "限守㓙神有根苗则不须畏惧")
        self.assertEqual(text_corrections["ocr-088"][1], "休囚者身性卑㣲旺相者名利壮寔")
        self.assertEqual(text_corrections["ocr-089"][1], "越外若贪必招㓙事噫甘贫养拙")
        self.assertEqual(text_corrections["ocr-090"][1], "葢人自生至老必从㣲以至少壮十嵗之时方当少年")
        self.assertEqual(text_corrections["ocr-091"][1], "欲交不交尚有㡬残之祸")
        self.assertEqual(text_corrections["ocr-092"][1], "吉运未到先作福㓙运过去始为殃")
        self.assertEqual(text_corrections["ocr-093"][1], "到死絶乡主骨肉死䘮自身衰祸钝闷百事蹇塞")
        self.assertEqual(text_corrections["ocr-094"][1], "有一字者㐫半二字俱无㓙莫能觧")
        self.assertEqual(text_corrections["ocr-095"][1], "巳酉之类谓之君臣庆㑹在两旬内")
        self.assertEqual(text_corrections["ocr-096"][1], "甲午见巳未之类谓之夫妻聚㑹")
        self.assertEqual(text_corrections["ocr-097"][1], "日月十二辰交㑹之所凡月之㑹朔日之璧于此位")
        self.assertEqual(text_corrections["ocr-098"][1], "谓之㑹劣谓之集十二月之辰")
        self.assertEqual(text_corrections["ocr-099"][1], "一嵗十二㑹太隂太阳隔液坎离之妙")
        self.assertEqual(text_corrections["ocr-100"][1], "此生万转图而放㑹合得可见也")
        self.assertEqual(text_corrections["ocr-101"][1], "故子与丑合得日月㑹同之数")
        self.assertEqual(text_corrections["ocr-102"][1], "所以在一旬内见方曰君臣庆㑹仍要别其阳为君")
        self.assertEqual(text_corrections["ocr-103"][1], "四冲生处自贫寒更值㓙神不足看")
        self.assertEqual(text_corrections["ocr-104"][1], "丁禄午见庚午截路空亡㐫壬午为徳合禄甲午为进神禄俱吉丙午喜神禄交羊刃半吉戊午伏羊刃禄多㐫")
        self.assertEqual(text_corrections["ocr-105"][1], "癸禄子见甲子进神禄主登科进达丙子交羊刃禄带福星贵有权戊子伏羊刃合贵禄半吉庚子印禄吉壬子正羊刃禄㐫")
        self.assertEqual(text_corrections["ocr-106"][1], "凡人命带禄或吉或㐫或贵或贱未可全靠便为吉论天乙妙㫖云")
        self.assertEqual(text_corrections["ocr-107"][1], "贵人嗔则㐫来可见命中有贵不可就为吉论要当细详")
        self.assertEqual(text_corrections["ocr-108"][1], "庚寅谓之破禄半吉半㓙壬寅谓之正禄带截路空亡必为僧道")
        self.assertEqual(text_corrections["ocr-109"][1], "乙禄卯见乙卯谓之喜神旺禄主吉丁卯为截路空亡主㐫己卯进神禄辛卯破禄又为交神半吉半㐫癸卯带太乙死禄虽贵终贫")
        self.assertEqual(text_corrections["ocr-110"][1], "丙禄己见己巳九天库禄主吉辛巳截路空亡癸巳伏贵神禄半吉半㐫乙巳旺马禄丁巳库禄俱吉")
        self.assertEqual(text_corrections["ocr-111"][1], "己禄午见庚午截路空亡壬午死鬼禄俱㐫甲午进神合禄显达之象丙午喜神禄戊午伏神羊刃禄㐫")
        self.assertEqual(text_corrections["ocr-112"][1], "庚禄申见壬申为大败禄甲申截路空亡禄俱㐫丙申大败禄多成败")
        self.assertEqual(text_corrections["ocr-113"][1], "辛禄酉见癸酉伏神禄水火相犯㐫乙酉破禄成败")
        self.assertEqual(text_corrections["ocr-114"][1], "八曰䭾屍十二驿马惟䭾屍最㓙见禄即屍")
        self.assertEqual(text_corrections["ocr-115"][1], "皆䭾屍也余旬凖此")
        self.assertEqual(text_corrections["ocr-116"][1], "乘轺则带职乘轩则三公䭾屍则得官即亡")
        self.assertEqual(text_corrections["ocr-117"][1], "如专羊刃主眼露性急㓙暴害物亲近恶党")
        self.assertEqual(text_corrections["ocr-118"][1], "亡神锦里一名儿女亡神岁去生他遇孤隔刼煞则㓙带禄贵则吉一重为妙又与日辰相统兼推吉㓙")
        self.assertEqual(text_corrections["ocr-119"][1], "㐫则昏浊邪侈毒害性重宿疾刑徒兵刀折伤")
        self.assertEqual(text_corrections["ocr-120"][1], "㓙则褊躁性窄顚诈狂妄浮荡是非酒色风流官府狱讼疽㾿气血气")
        self.assertEqual(text_corrections["ocr-121"][1], "其神最尊贵所至之处一切㓙煞隐然而避")
        self.assertEqual(text_corrections["ocr-122"][1], "夫徳者利物济人掩㓙作善之谓也")
        self.assertEqual(text_corrections["ocr-123"][1], "贵神在位诸煞伏藏二徳扶持众㓙解散凡命中带㓙煞得此二徳扶化㓙不为甚须要日上见时上不犯尅冲刑破方吉凡人得之一生安逸不犯刑不逢盗纵遇㓙祸自然消散")
        self.assertEqual(text_corrections["ocr-124"][1], "更有月徳并者尤好纵有㓙煞亦主清显")
        self.assertEqual(text_corrections["ocr-125"][1], '午己未气过阳宫重离相㑹炳灵交光发辉炎上乃曰')
        self.assertEqual(text_corrections["ocr-126"][1], '华葢悬针破字】\n 壬申金【戈㦸大喜子午卯酉平头大败')
        self.assertEqual(text_corrections["ocr-127"][1], '荧煌寒林缀叶之光隔幔㸃衣之彩方朔以萤火名之')
        self.assertEqual(text_corrections["ocr-128"][1], '相资主贵大林有风杨柳㑹火二木最忌桑柘癸丑为')
        self.assertEqual(text_corrections["ocr-129"][1], '命爱申年亥时乃地天交㤗\n 已为大驿大驿者人烟凑')
        self.assertEqual(text_corrections["ocr-130"][1], '未乃木库如人筑墙垣以䕶百花也以百花言未中有')
        self.assertEqual(text_corrections["ocr-131"][1], '也其禽蛇子亦水也其禽䑕午亦火也其禽马水胜火故豕食蛇火为水所害故马食䑕屎而腹胀然亦有不相胜者午马也子䑕也酉鸡也卯兔也水胜火䑕何不逐马金胜木鸡何不啄兔亥豕也未羊也丑牛也土胜水牛羊何不杀豕巳蛇也申猴也火胜金蛇何不食猕猴猕猴畏防者也囓猕猴者犬也防水猕猴金也水不胜金猕猴何故畏䑕戌土也申猴也土不胜金')
        self.assertEqual(text_corrections["ocr-132"][1], '如人生后三日以沐浴之㡬至困絶也六曰冠带万物')
        self.assertEqual(text_corrections["ocr-133"][1], '得位本胜于主者多得祖䕃主胜于本者当自卓立本主两强富贵双全四柱中更抑扬归中无太过不及方作好命有一位不及必主蹇滞然诸家命术皆云好年不如好月好月不如好日好日不如好时大率以年则统乎一嵗月则该乎三十而时日为得之独不知得日时之吉而月不应反为无用况用神多取诸月是月又可轻乎唐李虚中独以日干为主却以年月时合㸔生尅制化旺相休囚取立')
        self.assertEqual(text_corrections["ocr-134"][1], '发福于生时日者三阳之㑹帝皇之象时者近侍之臣')
        self.assertEqual(text_corrections["ocr-135"][1], '运尅嵗与日犯同主破耗䘮事有贵人禄马觧之稍吉')
        self.assertEqual(text_corrections["ocr-136"][1], '嫉妬相害故酉人见戍则㓙戍人见酉无灾若乙酉人')
        self.assertEqual(text_corrections["ocr-137"][1], '鬼在己上为害以三合相㑹在辰则减福以六合相亲')
        self.assertEqual(text_corrections["ocr-138"][1], '下生人月日时支干得御䇿全并尅身者定贵马前一辰为御后一辰为䇿假令甲子金命正月辛丑日卯时生以子人马在寅逢禄又本命子与生日丑在马后为䇿卯时在马前为御又马是')
        self.assertEqual(text_corrections["ocr-139"][1], '爱子午相冲为飞马见鞭䇿入格主贵\n 有驿马清浊甲子得丙寅禄马同乡又丙为食神乘长生马丁丑得丁亥为天乙天官乘临官马若乘长生临官马或带食禄贵气则遇一当百若乘病絶空亡马更値破败交退伏神则遇而不遇纵为官粗浊卑贱非清要之职\n 又曰凡看驿马有四专名位生旺病絶駞宝啣花及倒食互换不同中间好恶荣辱须于岁运鞭䇿细详之四专者如申子辰')
        self.assertEqual(text_corrections["ocr-140"][1], '在申冲动寅即太岁为鞭䇿小运在申即小运为鞭䇿多主动更看申与寅互换')
        self.assertEqual(text_corrections["ocr-141"][1], '分优劣即前六十甲子吉㓙其归要与禄马同窠不犯')
        self.assertEqual(text_corrections["ocr-142"][1], '勲业超羣带天月二徳者㓙灾不犯带六仪者才智出')
        self.assertEqual(text_corrections["ocr-143"][1], '恶死若旌钺更与三公煞㑹同一位主殊贵今之谈命')
        self.assertEqual(text_corrections["ocr-144"][1], '命无福神往还名带煞主㓙\n 有临空印乃印落空亡支无六合见官贵至贱而无成也\n 有自刑印如庚戌人带乙丑金人见金印固好丑戌相刑以金刑金此类不如无虽有少福亦终贱余准此推\n 凡论印更得眞五行与纳音同气尤妙但主少安逸不利六亲难为子息\n 论徳秀\n 夫徳者本月生旺之徳秀者合天地中和之气五行变化而成者也又曰徳者阴阳解㐫之神秀者天地清秀之气')
        self.assertEqual(text_corrections["ocr-145"][1], '于三合细推排天盘加得㐫星到命似风灯不久摧水')
        self.assertEqual(text_corrections["ocr-146"][1], '居此地贫穷蹇滞过平生㓙星恶曜如临到大限浑如')
        self.assertEqual(text_corrections["ocr-147"][1], '则为福已极则将反而为㓙极盛之地十干中正处是')
        self.assertEqual(text_corrections["ocr-148"][1], '未甲辰乙卯壬子癸丑皆㓙象也金紧木慢女命犯之定尅夫害子不贞洁理愚歌云倒悬羊刃又同行形骸不免塡沟壑又云飞刃倒戈终见乖小人得此便为灾空亡截路同相见此身安得出尘埃又云羊刃更兼倒戈必作无头之鬼是羊刃带诸恶煞尤㓙\n 凡人行运最怕羊刃主作')
        self.assertEqual(text_corrections["ocr-149"][1], '生破散与咸池六害并多㐫暴卒惟夹贵华盖三竒学')
        self.assertEqual(text_corrections["ocr-150"][1], '两号天中见合长生旺不㓙加临冲尅兼刑禄官职陞')
        self.assertEqual(text_corrections["ocr-151"][1], '正余干午未半之所以为㐫者当气冲之地左鼓则风煞在右右鼓则风煞在左故阴阳男女取冲前冲后不同若岁运临之如物当风动摇顚倒不得宁息不有内疾必有外难虽富贵崇高势位炎盛大运逢之十年可畏立朝定当窜逐居家必罹㓙咎纵有吉神扶持不免祸福倚伏尤忌先吉后㓙临旺之后欲出未出之际㓙祸尤的生命逢之主形骸')
        self.assertEqual(text_corrections["ocr-152"][1], '贱格再値一切防神则愈㓙又曰金生处主大风瘫痪')
        self.assertEqual(text_corrections["ocr-153"][1], '杖刃土坠落瘟疫尅身大㓙若有福神相助多是武权亦如刼煞之类要见官星印绶生旺处为佳神白经云灾煞畏乎尅生处却为祥正谓此也\n 论六厄\n 厄者遭乎难者也常居马前一辰刼后二辰死而不生谓之厄申子辰水局水死在卯寅午戌火局火死在酉亥卯未木局木死在午巳酉丑金局金死在子所以为厄若有救䕶有扶持逢生旺兼贵气相')
        self.assertEqual(text_corrections["ocr-154"][1], '此煞大忌金神白虎并则㓙牛马犬畜等伤亦是不独虎狼也不尅身与福同宫者不用大抵此煞凡命遇之身若尅煞多心路计巧主掌刑法之任或为将帅专行诛戮煞若尅身主非命而终小人逢之非横灾祸行年至此亦主口舌刑狱等事又云値两位全者灾重一位者轻又云有鬼则灾重无鬼则灾轻\n 论孤辰寡宿【及隔角煞】\n 先贤有云老而无夫曰寡㓜而无父曰孤此其义也辰')
        self.assertEqual(text_corrections["ocr-155"][1], '亲不聚财多生女更带诸㓙煞主不令终珞琭子云凭')
        self.assertEqual(text_corrections["ocr-156"][1], '交战大败无一生还喻极㐫也六甲旬中十个日値禄')
        self.assertEqual(text_corrections["ocr-157"][1], '更有天中官符大耗者定㓙\n 水溺煞 此煞取丙子癸未癸丑上带咸池金刃羊刃盖丙子纳音水又子为水旺之地未为井宿之居丑为三河之分更纳音尅身决不可免古歌云刼煞尅身名顚坠金神羊刃防同位要知自缢最㓙神戌巳辰亥并寅未子酉一例为㓙煞卯申丑未依前是大忌空亡兼墓鬼官符大耗仍须避丙子癸未并癸丑咸池金煞羊刃畏五行更若来尅身一死悬梁一溺水\n 挂劒煞 此煞取己酉丑申四柱纯全者是或重带已酉丑亦是更犯官符元辰白虎金神等类五行刑尅本命者主㓙暴杀人或反为人所杀诗')
        self.assertEqual(text_corrections["ocr-158"][1], '刃的煞飞廉等会命限必㓙主堕于天眞雷伤虎啗天')
        self.assertEqual(text_corrections["ocr-159"][1], '月时日犯之无贵神解救㓙恶短折\n 丧吊煞 一名横关煞取命前二辰为丧门命后二辰为吊客其或太岁㐫煞并临大小运限必主祸古诗云五官六死十二病三丧十一吊来临可见此十二宫一太岁歌不惟命犯不吉流年尤㓙若月有羊刃来佐㐫煞临时则横关也古歌云横关恶煞少人知月禄㓙神又及时纵有吉星重疉')
        self.assertEqual(text_corrections["ocr-160"][1], '旺干加临日时带两重者㓙更与悬针相见主决配伤残\n 浮沉煞【血刃同】从戌上起子逆行至本生年住却从年宫数看在何宫只在财帛宫名串钱主富蓄余皆㓙甲乙己庚壬人犯之稍轻')
        self.assertEqual(text_corrections["ocr-161"][1], '之\n 以上诸煞凡言尅身谓㓙煞下纳音尅生年太岁纳')
        self.assertEqual(text_corrections["ocr-162"][1], '令得旺气忌有败之者凡㓙神欲令得衰气忌有助之者又云相冲相破三合六合命中有之即求五行相得何如或祸中生福福中生祸如死絶复生空亡受破相尅相成则祸中生福反此则福中生祸命书云道途贱吏岂无驿马攀鞍市井博徒亦有三奇夹贵子平云君子格中也犯七煞阳刃小人命内亦有正印官星由是观之吉㓙神煞不可拘定轻重较量要在通变大抵㐫煞所居于神不宜带真鬼')
        self.assertEqual(text_corrections["ocr-163"][1], '坐支兼得月时及行运吉㓙\n 甲乙\n 甲木属阳乃栋梁之')
        self.assertEqual(text_corrections["ocr-164"][1], '鬼论分身鬼强弱定其吉㐫寿夭若制伏得中作偏官论太过反不为福更㸔日干于所生月内有力无')
        self.assertEqual(text_corrections["ocr-165"][1], '岁君相犯官府刑狱破财䘮服生于秋冬更遇夜时地')
        self.assertEqual(text_corrections["ocr-166"][1], '论要分身鬼强弱定其吉㓙寿夭制伏得中作偏官用')
        self.assertEqual(text_corrections["ocr-167"][1], '论要分身鬼强弱定其吉㓙寿夭制伏中和作偏官用')
        self.assertEqual(text_corrections["ocr-168"][1], '论要分身鬼强弱定其吉㓙寿夭制伏得中作偏官论')
        self.assertEqual(text_corrections["ocr-169"][1], '论要分身鬼强弱定其吉㐫制伏得中作偏官论制过')
        self.assertEqual(text_corrections["ocr-170"][1], '杂有煞无制鬼论制太过㓙更详日干于月令内有无力助轻重言之运喜忌同上\n 论十二月支得日干吉㐫\n 子月\n 甲乙日得子月为印')
        self.assertEqual(text_corrections["ocr-171"][1], '生又自坐禄何夭之有更㸔壬露无丙癸露无丁甲露')
        self.assertEqual(text_corrections["ocr-172"][1], '正官\n 论五行时地分野吉㓙\n 按王氏所谓二气者阴阳')
        self.assertEqual(text_corrections["ocr-173"][1], '性流荡离祖迁居土金水㑹夭折无疑贱贫而寿逢金伐之旺处遭伤斨其生意岂天地生物之至仁耶先正有云春木虽旺不宜逢金者此也\n 三月之木正条达长茂之时春阳和照万紫千红雨水浸滛根株摇动见土则根深蒂固福寿绵延见火则木通火明文章秀发逢金伐木荆梁生者㐫徐扬之人富贵喜火土忌金水运喜东南西北不利夏木病已死午墓未者盖南方火盛泄其眞气故也阴雨则吉亢晴则忌\n 四月木未甚衰火未甚旺见㣲火则枝叶茂繁荫庇发福値盛水则水神飘荡男女滛奔见土利就名成火土同躔干支有壬癸亥子者富贵逢金尅之灾讼不免徐扬人反吉\n 五六月之木喜雨水夜生尤竒値此者富贵而寿火盛无水者贫夭夏令炎威火盛烁石流金木有枯槁之患徐扬人干火多者有疯痨荧燎之㓙或水制或夜生或阴雨天')
        self.assertEqual(text_corrections["ocr-174"][1], '梁生者忌之金水同行化㓙为吉逢土培植利就名成水盛无土冀雍飘荡无居徐扬人反㓙成吉八九月之木正凋零')
        self.assertEqual(text_corrections["ocr-175"][1], '木正肃杀之时复命归根㣲有小春生意以见造化无终穷之理易曰硕果不食者此也生于晴明者最佳値阴雨则凝氷积雪也\n 十月之木遇火贵而有寿盖氷寒土冻仗火以温暖其根故也火土辅运富贵双全见金虽无害其根本未免骨肉参商得水则有滋助之意徐扬人利就名成冀雍人贫寒孤尅\n 若子丑月之木喜火融之与土同躔位登台鼎见水㐫尅盖冬水令也木寒木也')
        self.assertEqual(text_corrections["ocr-176"][1], '冀雍之人尤甚见土盗泄㣲阳浮薄卑贱二月见木败处逢生木秀火明文章富贵人也但不宜有水盖湿木不生无焰火也谷雨之后生者防水无㐫盖土司时木主令化防而为吉也兖青徐扬生者富贵何疑土与金正月同论但辰月土差旺耳\n 夏令之火阳气之极草木为之焦枯江河为之枯涸晴则流金烁石眞阳尽泄雨则水济其威方得中和反应荫庇发福四月火势渐盛逢日争光未能全其忠爱虽富贵亦主夭亡贫寒者寿而多子孤独艰辛见金名成利就逢土有权有谋遇木富而好礼㣲水济木其贵不可言也\n 五')
        self.assertEqual(text_corrections["ocr-177"][1], '利就日战月刑忠孝有亏㐫祸孤尅夜生减轻气运宜徃西北南东大忌\n 秋初之火炎威未退土传生气水不能尅反主贵荣见木助之徐扬兖青人干支火多者虽富贵而寿不永见金为财富贵豪侈逢土则息显达非常\n 八九月失时之火见木生生之意无穷富贵无敌金木同躔官居宰辅有金无木主弱敌强不免有争攘之事冀雍荆梁人因财致祸与土同躔泄其眞元孤刑冷退得木助之斯为美矣见水㐫夭运喜东南西北忌之冬月之火人多亲之晴霁则明阴雨则㓕故见水为㐫木生为贵有水无木轻者疾重者夭虽生富厚之家不免冷退徐扬兖青人得水制之无咎逢土泄之弱中又弱蹇滞终身小寒之后旺土晦其光明定主昏愚瞽目见金为财青兖徐扬人主富荆梁冀雍人助难为㓙谓金之子水也克其母子则乘势报仇无木觧之有刀兵狱讼之厄肿痢没溺之㓙干支木盛者减轻大抵冬')
        self.assertEqual(text_corrections["ocr-178"][1], '火同躔位登台鼎见水则㓙冀雍青兖人土浑水浊终有水涌土溃之危盖水生旺木而伤土也値此者贫寒疾夭徐扬豫人干支火者反吉见金以泄土气难免灾㐫\n 三月之土渐有生意盖土旺季月故也有火温燠则阳气发舒而生物茂矣见木非疾则夭徐扬豫人无害水木同度贫薄无聊冀雍兖青人尤甚见金制木反㓙成吉运喜南方西方次之')
        self.assertEqual(text_corrections["ocr-179"][1], '和而万物归根矣见木则㐫逢金则滞遇水则主孤寒')
        self.assertEqual(text_corrections["ocr-180"][1], '困滞之灾盖春木盛旺以㣲弱之金而欲制之是犹以')
        self.assertEqual(text_corrections["ocr-181"][1], '轻者疾重者夭得水济之㓙中反吉见木亦主富贵豪')
        self.assertEqual(text_corrections["ocr-182"][1], '徳未免痰疾刑伤见土虽㓙不㓙盖秋令金最能化难为福')
        self.assertEqual(text_corrections["ocr-183"][1], '父母之义故立名印绶印䕃也绶受也譬父母有恩徳䕃庇子孙子孙得受其福朝')
        self.assertEqual(text_corrections["ocr-184"][1], '许一位多则不宜正官先㸔月令然后方㸔其余以五行之气惟月令')
        self.assertEqual(text_corrections["ocr-185"][1], '生无疑时为归息之地吉㐫全在时消息日主用神太盛宜时以节制之日主用神渐衰宜时以补助之柱中虽有㐫神时能节制亦不能为祸此㸔命之要法也又曰甲生丑')
        self.assertEqual(text_corrections["ocr-186"][1], '渐弱官随合神谓之贪合㤀官又曰正官格要行印乡')
        self.assertEqual(text_corrections["ocr-187"][1], '运流年逢之灾尤重此亦㸔官星者所当知喜忌篇云')
        self.assertEqual(text_corrections["ocr-188"][1], '时破害冲空俱不犯富贵䨇全报尔知【又】官星不可被刑冲官煞同来吉变㓙化煞为官方是吉化官为')
        self.assertEqual(text_corrections["ocr-189"][1], '官同论遇此必生宦族或䕃袭祖父之职若月居财官分野运向财官旺地日主徤旺贵无疑矣凡年干遇官福气最重发达必早如癸酉庚申丙子丙申年上官星柱中㑹官局归禄日下丙克申酉金为财官䨇美二丙身旺十七八运行戊午虽午冲子申子㑹局冲不能动日主并旺及第早发古歌云年中正禄是根芽必主生身富贵家运气喜逄身旺地财生印助福无涯【又】年上官星为嵗徳喜逄财印旺身宫不逄七煞偏官位富贵荣华莫与京\n 时上正官\n 如甲日酉辛时乙日申庚时例时上官星与月亦同但力轻㣲发福多在晚年或生贤子')
        self.assertEqual(text_corrections["ocr-190"][1], '贵人卯刑子子刑卯癸乙䨇䨇富又清未刑戌戌刑未甲')
        self.assertEqual(text_corrections["ocr-191"][1], '战故谓之七煞譬小人多㓙暴无忌惮若无礼法控制之不惩不戒必伤其主故有制谓之偏官无制谓之七煞如日主徤旺有印绶助化即经云煞见印而显煞助印生有财星生扶即经云逄煞防财如身强煞弱有财星则吉身弱煞强有财引鬼盗气非贫则夭有食神透制即经云一见制伏却为贵本有阳刃配合即经云煞无刃不显逄煞防刃是也以上诸制合生化须要无太过不及是借小人势力卫䕶君子以成威权乃大权大贵之命又性格聪明忌日主衰弱七煞重逄三刑六害刼亡相并魁罡相冲其㓙不可具述若七煞止一而')
        self.assertEqual(text_corrections["ocr-192"][1], '柱中不透火制地支子辰㑹印成局则煞生印印生身作权贵㸔年干露煞与月令时支不同太嵗乃一生之主最重如甲见庚年乙见辛年又生申酉丑月柱中金多大运再行金乡流年嵗君并见为㓙尤甚若生寅午戌及木旺')
        self.assertEqual(text_corrections["ocr-193"][1], '印无煞欠威风絶妙煞印䨇全宜其文武两备玄机赋')
        self.assertEqual(text_corrections["ocr-194"][1], '客古歌云偏官不可例言㓙有制还他衣禄丰干上食神支带合儿孙满眼受褒封【又】身逄七煞是提纲只为干衰大受伤正禄交差刑煞入终身不免受㓙殃【又】七煞提纲本是愁只')
        self.assertEqual(text_corrections["ocr-195"][1], '乃时逄七煞见之未必为㓙月制干强其煞反为权印')
        self.assertEqual(text_corrections["ocr-196"][1], '主徤旺老仆则尽力以事㓜主日主衰弱不能与小人为主何肯尽力事之反成害己之物年干见此必主出身寒㣲四柱行运有情主寒门生')
        self.assertEqual(text_corrections["ocr-197"][1], '又忠贤【又】年干七煞莫言㓙制合为权最有功若得身强无忌破此身多入禁庭中【又】嵗伤日干不和同须要干支制伏重煞旺喜行身旺地初年难免一塲防\n 弃命从煞\n 独歩云弃命从煞须要㑹煞从财忌煞从煞喜财防逄根气命损无猜葢言从煞格以煞神太重身无所归不得已从之要行煞旺及财乡四柱无一㸃比肩印绶方论如遇运扶')
        self.assertEqual(text_corrections["ocr-198"][1], '旺又曰鬼多无鬼反不为㓙古歌曰五阳坐日全逄煞')
        self.assertEqual(text_corrections["ocr-199"][1], '煞留官者即以正官论凡㸔去留要详柱中官煞孰重')
        self.assertEqual(text_corrections["ocr-200"][1], '七煞两均相停有物生扶㑹和者其力专宜存而留之')
        self.assertEqual(text_corrections["ocr-201"][1], '不遂故曰贪合忘官大抵㓙神有物合去则反㓙为吉吉神有物合去则反吉为㓙吉㓙神煞㸔局中喜忌何神不可执一论奥㫖赋云阳日食神暗合官星')
        self.assertEqual(text_corrections["ocr-202"][1], '非忽然癸水来相助合住㓙顽不见威此贪合忘煞例')
        self.assertEqual(text_corrections["ocr-203"][1], '神康强而后可享用若衰㣲不振虽妻财丰厚但能目')
        self.assertEqual(text_corrections["ocr-204"][1], '财\n 独步云弃命从财须要㑹财若逢根气命损无猜假')
        self.assertEqual(text_corrections["ocr-205"][1], '卯未人见戊辰此妻财聚㑹之神遇者主富足及有美')
        self.assertEqual(text_corrections["ocr-206"][1], '气之源为生气为父母能䕶我官星使无伤尅譬人生')
        self.assertEqual(text_corrections["ocr-207"][1], '绶不逢损伤多受父母倚䕃资财见成安享富贵诸命')
        self.assertEqual(text_corrections["ocr-208"][1], '或印绶死絶或临墓地皆㓙经云煞能生印畏行财乡')
        self.assertEqual(text_corrections["ocr-209"][1], '帮万祺赋云正印见财则㓙逢官则吉有官无印纵富')
        self.assertEqual(text_corrections["ocr-210"][1], '心虗凡事无成尅害六亲㓜时尅母长大伤妻子赋云')
        self.assertEqual(text_corrections["ocr-211"][1], '死絶有福神加临则减退㫁之若尅破而无福神只是')
        self.assertEqual(text_corrections["ocr-212"][1], '纲不可冲十冲九命皆为㓙惟有财官逢墓库运行到')
        self.assertEqual(text_corrections["ocr-213"][1], '余蕴矣\n 附论墓运\n 秘诀云㓜年不宜逢墓库老年值此')
        self.assertEqual(text_corrections["ocr-214"][1], '官祸患百端是也伤官虽㓙乃我所生自家之物伤尽则能生财财旺则能生官造化展转有情如月令在伤官四柱作合结局皆在伤位无冲无破不见一㸃官星谓之伤尽又有月支')
        self.assertEqual(text_corrections["ocr-215"][1], '官既无官星而柱却无一㸃财可恃虽聪明机巧不过')
        self.assertEqual(text_corrections["ocr-216"][1], '运行东南火旺之乡无一㸃财气身空旺无倚至贫之')
        self.assertEqual(text_corrections["ocr-217"][1], '逐马主为人退悔反伤祖䕃运行官乡流年再见或煞')
        self.assertEqual(text_corrections["ocr-218"][1], '柱见财食在嵗月上祖父䕃业丰隆在日时妻男获福')
        self.assertEqual(text_corrections["ocr-219"][1], '庚以壬为食长生于申当㫁申地福重暴败在酉壬水至酉便不为佳以壬生甲木为庚之财即自生分发身之财非婚配正妻之财甲至酉地为木困金乡壬水自败木岂能助养其父当断此运平平行至戌运如干遇壬甲亦只㫁其半吉半㓙逢戊可㫁其有灾见庚可㫁其㣲福亥运当言其大吉子运癸水伤官伤重泄本身之气又庚死于子甲败于子当㫁生祸身灾运至丑庚金之库水旺之乡又有已丑助庚甲冠带成人之地可㫁此十年发寅运亦吉卯运')
        self.assertEqual(text_corrections["ocr-220"][1], '命多被人挠重叠带者在㓜儿则言乏乳在老人则言缺食正食而有余者富贵争食而不足者贫贱有余如甲人得两丙三丙不足如柱中两甲止有一丙之类又曰日主时干重叠相食者曰吞㗖脑子时日俱食主头风脑')
        self.assertEqual(text_corrections["ocr-221"][1], '之不可当若无偏财来救䕶命如秋草带冬霜【又】食神月上号天厨人命逢之富有余切忌枭来明减福最嫌冲去暗消除生财化鬼兼无病制煞为祥信有储士子如逢利甲第官封要职领天书合诸说观食神喜忌尽矣\n 飞天禄马\n 喜忌篇云若逢伤官月建如㓙处未必为㓙内有倒禄飞冲忌官星亦嫌羁绊此格惟有四日庚子壬子辛亥癸亥生十月十一月冬水纯隂柱无财官方用又须月时或年与日同支方能并冲忌官星显露禄难飞冲合神覊绊不能飞冲要柱中有一字合住禄马方不走了贵气喜伤官食神及干文本运假令庚子日庚以丁火为官在子月生是伤官月建可谓㓙处若子字多冲出午中丁火则庚日得官星未可便以㓙论柱要有未或寅戌但得一字合午为妙若有丑覊绊子去贪合不能冲午中之禄见丁字为官露丙为煞显午字填实戊吞㗖则减分数嵗运同壬子日')
        self.assertEqual(text_corrections["ocr-222"][1], '木阴金尅阴木至毒所以㓙与阳刃同阳刃有三有刼财刃甲见乙是也不利财官格有䕶禄刃甲见卯是也大利归禄格有背禄刃乙丙是也大利去官留煞局喜忌篇云刼财阳刃切忌时逄歳运并临灾殃立至独阳刃以时言重于年月日也假令甲日生人时上见乙卯此是真刃命中既逄阳刃伤妻破财灾殃已胚胎矣流年歳运再遇羊刄是谓并临见己酉是冲歳君见亥未戌是合歳君阳刃防煞也太岁㓙神也太岁得吉神相扶合则吉若阳刃㓙煞来冲合岁君是谓攅防聚煞其祸难免经云阳刃冲合岁君勃然祸至此之谓也中间亦要详辨命元浅薄遇此诚然若命旺秉气深厚或有天月徳及赦文解救止有浮灾亦无大咎或曰柱原有刃见冲或合岁运再临冲合大㓙若岁冲合而运不冲合运冲合而岁不冲合其祸减半论又曰日干无气时逄阳刃不为防言生日天元临死絶衰病暴败之地不通月气不能胜任财官若逄阳刃能刼财化煞譬如兄力弱财重得弟分任则可胜其财而为我用所以不作㓙论夫身弱见财官固喜阳')
        self.assertEqual(text_corrections["ocr-223"][1], '疆如更无情或临财旺主㓙若刑害俱全类皆得地又')
        self.assertEqual(text_corrections["ocr-224"][1], '辅甲为贵能尅破乙煞反㓙为吉经云甲以乙妹妻庚㓙为吉兆是也余干例此又曰六甲日逄乙卯防辛卯吉甲申丁卯不为刃申中有庚合卯中乙木为财若有财露亦㓙丁火伤官乙木夺财岁运')
        self.assertEqual(text_corrections["ocr-225"][1], '见七煞七煞喜见阳刃两㓙互相制伏犹正官喜正印')
        self.assertEqual(text_corrections["ocr-226"][1], '三日也不喜刑冲破害三㑹六合要有七煞相制再行官印乡便为好命赋云日刄大忌冲合喜官煞相制合刑者凶遇印者吉有煞无刃施为有勇无威有刄无煞作事浊而不显无煞遇煞窃恐祸患相侵有刄遇刄须忌灾危相犯刄生身死其年难作吉推财旺官伤此岁不作㓙㫁又曰戊午日岁月见火多')
        self.assertEqual(text_corrections["ocr-227"][1], '心性气髙强刑冲太重多㓙厄有制方能保吉昌【又】刃逄七煞慕官乡惟怕刑冲禄不昌㑹合更逢财旺运预防灾祸')
        self.assertEqual(text_corrections["ocr-228"][1], '前性刚果毅少慈怜不宜㑹合防灾至若见财星祸必纒有官有煞名显逹无冲无破禄荣迁更加刑害魁罡并发迹邉疆掌重权又离火怕重逢北方喜有功虽然宜见水犹恐对提冲如一命壬申壬子戊午乙卯自坐阳刃二壬申子财旺且多子午虽冲申子㑹午不能冲时官星制伏阳刃只作财官格㸔所以大贵又一命丙戌癸')
        self.assertEqual(text_corrections["ocr-229"][1], '若柱不见财官印食同前㫁丙生巳月嵗时干支水金成局运歴财官旺地亦主富贵丁生午月金败水絶财官俱背顺运尅妻逆运尅三妻若柱有巳酉丑庚辛壬癸亥申子辰运临财官旺地亦发用煞或印以多为贵若止建禄亦同前㫁戊日巳月年日时无水主')
        self.assertEqual(text_corrections["ocr-230"][1], '矣若年日时多带财好命㸔见丙丁巳午寅戌火局则')
        self.assertEqual(text_corrections["ocr-231"][1], '运壬申年不禄嵗运冲且㑹伤官煞也建禄用财官伤')
        self.assertEqual(text_corrections["ocr-232"][1], '常柱中俱有寅辰字富贵䨇全在庙堂【又】壬骑龙背喜')
        self.assertEqual(text_corrections["ocr-233"][1], '得合癸是谓巳酉丑三合㑹起官星局年月大怕有午')
        self.assertEqual(text_corrections["ocr-234"][1], '赋云】卯破午午破酉财官䨇美【又云】年日支无破官之辰月时支有破官合官之辰主贵如甲寅日无破月逄丙午时临巳已此取午破酉中辛官有巳合之又用巳中丙戌合辛为贵【诗曰】卯破午未有大官午未破酉一般㸔丑破巳午不为例子破卯辰用不难\n 飞财\n 日干同月干日支同时支冲出对宫之财是也得此格当发财禄忌泄气㐫如壬申日生时支亦申二')
        self.assertEqual(text_corrections["ocr-235"][1], '不意之财【诗曰】命里无财㸔破财破来财禄似山堆运行官印多多福却怕刑冲塡实灾【又】卯破午未取财㸔午未破酉总一般丑破巳')
        self.assertEqual(text_corrections["ocr-236"][1], '云】隂木独遇子时为六乙䑕贵之地乙以子申为贵神独遇子者用䑕不用猴也乙用庚金为官星得丙子时以子上丙火遥归巳中本禄巳来合申申来动子是谓申子辰三合㑹贵谓申中带将庚来乙日')
        self.assertEqual(text_corrections["ocr-237"][1], '用不以午冲子为祸如合䑕贵柱有未合午畧有损坏富而虚名【相心赋云】六乙䑕贵遇午冲而赤贫如洗【眞')
        self.assertEqual(text_corrections["ocr-238"][1], '是时上偏官不作归禄格㸔四柱何如若月有官星或')
        self.assertEqual(text_corrections["ocr-239"][1], '官临巳用神坐贵得财官䨇美故少年及第中年拜相三曰归禄逄二德如辛亥辛卯甲寅丙寅甲专禄而得丙寅为食㑹禄甲为月德月令辛卯为')
        self.assertEqual(text_corrections["ocr-240"][1], '身申庚伤甲不能生财为㐫【又曰】壬日多见寅字用寅')
        self.assertEqual(text_corrections["ocr-241"][1], '癸日坐向巳宫乃是财官䨇美禄即官财即马二句同')
        self.assertEqual(text_corrections["ocr-242"][1], '生金木月贵惟忌土重若㑹起土尅官主富己亥日宜')
        self.assertEqual(text_corrections["ocr-243"][1], '刑冲煞刄如来见反吉为㐫不可当【又】癸临蛇兎是英')
        self.assertEqual(text_corrections["ocr-244"][1], '一脱乎此亦能再发终力㣲此格只一位喜财官日徳重叠不宜见财官及刑冲破害空亡魁罡㑹合加临皆为大忌【诗曰】壬')
        self.assertEqual(text_corrections["ocr-245"][1], '位即以财官印食取用虽㣲有破败财官印食得位亦')
        self.assertEqual(text_corrections["ocr-246"][1], '为贵大忌水局伤官重并㐫恶死于不义如遇土局火')
        self.assertEqual(text_corrections["ocr-247"][1], '巳坐财官号曰勾陈得位㸔知有大财分瑞气命中値')
        self.assertEqual(text_corrections["ocr-248"][1], '制之得成堤岸既有土怕㑹木为㐫如有木伤土要金印救解')
        self.assertEqual(text_corrections["ocr-249"][1], '之夹煞持丘骨肉离犯此㐫星无救助生来福夀少年')
        self.assertEqual(text_corrections["ocr-250"][1], '别之壬寅辛卯甲戌富贵䨇全己巳亦贵戊午丁未刃旺性强虽贵亦多㐫险尅妻不善终庚辰贵而')
        self.assertEqual(text_corrections["ocr-251"][1], '背必当大贵冲刑尅制亦㐫不可执定一气皆以贵言')
        self.assertEqual(text_corrections["ocr-252"][1], '享用过当故死公生于寒㣲未得享用故活后鄂官至')
        self.assertEqual(text_corrections["ocr-253"][1], '主病故也白浊白带霍乱㵼痢疝气小肠属肾家壬癸亥子受亏主病故也\n 甲乙见庚辛申酉多者内主肝胆惊悸劳瘵手足顽麻䈥骨疼痛外主头目眩晕口')
        self.assertEqual(text_corrections["ocr-254"][1], '和翻胃隔食气噎蛊胀泄㵼黄肿择拣饮食呕吐恶心')
        self.assertEqual(text_corrections["ocr-255"][1], '聋睛盲伤寒感冒外主风䖝牙痛偏坠肾气腰痛膝痛淋沥吐㵼怕冷恶寒女人白带鬼胎')
        self.assertEqual(text_corrections["ocr-256"][1], '相刑病生腰膝甲申乙酉㓜年多病肝经辛夘庚寅晚年劳伤䈥骨丙火上炎丈夫每忌于')
        self.assertEqual(text_corrections["ocr-257"][1], '疾内经云东方实西方虚㵼南方补北方东方实者木太过也西方虚者金不及也㵼南方者火太过也补北方')
        self.assertEqual(text_corrections["ocr-258"][1], '之疾 水土相尅主脾湿泄㵼中满痰嗽不利之疾\n 有相')
        self.assertEqual(text_corrections["ocr-259"][1], '为众隂伤官煞重主腰脚䈥骨之疾伤官伤尽者不在')
        self.assertEqual(text_corrections["ocr-260"][1], '子命如子命遇孤辰寡宿䘮门吊客及白衣煞临命其')
        self.assertEqual(text_corrections["ocr-261"][1], '夫星以定出身之贵贱再㸔子星以察晚年之荣辱官')
        self.assertEqual(text_corrections["ocr-262"][1], '有财生官有印助身无一㸃混浊之气方为清贵如【一')
        self.assertEqual(text_corrections["ocr-263"][1], '八专自旺丙火为夫寅戌㑹局时干又丁爱重火情庚')
        self.assertEqual(text_corrections["ocr-264"][1], '为子丙火长生于寅与戌㑹局皆属火月令既无金气')
        self.assertEqual(text_corrections["ocr-265"][1], '公夀难延财重叠婆年早䘮身居旺地虽富足夫子刑')
        self.assertEqual(text_corrections["ocr-266"][1], '枯\n 【又曰】年逢刃煞防年早䘮爹娘时遇刃伤末年却损')
        self.assertEqual(text_corrections["ocr-267"][1], '正财旺而身失时母年早䘮偏官偏印偏财叠逢必然')
        self.assertEqual(text_corrections["ocr-268"][1], '受伤旺子伤夫察官星而䘮絶女命印旺官轻夫权在')
        self.assertEqual(text_corrections["ocr-269"][1], '时财死墓絶败处定主尅䧟或一生鳏居若日禄在时上遇见如六丙日得癸巳时六壬日得辛亥时之类名名誉煞不惟主富亦主因妻有官若日带年之官或年之印主妻夺夫权或禄出妻䕃或妻权贵之家驸马郡马')
        self.assertEqual(text_corrections["ocr-270"][1], '浮主移根换叶申月煞星㑹印俱贵子月行水木运亦')
        self.assertEqual(text_corrections["ocr-271"][1], '甲戌日甲子时拱亥天门㑹同帝阙甲长生地也不可')
        self.assertEqual(text_corrections["ocr-272"][1], '若年日时合成火局得制㐲主徳性纯和而贵无火凶')
        self.assertEqual(text_corrections["ocr-273"][1], '神入火局身弱贫夭寅戌㑹火是一木叠逢火位不吉')
        self.assertEqual(text_corrections["ocr-274"][1], '运最吉亦有酉丑月贵者㸔干透及年何如\n 【己亥王大')
        self.assertEqual(text_corrections["ocr-275"][1], '贵己亥二三品辰子年月㑹水以煞化印吉未月财库')
        self.assertEqual(text_corrections["ocr-276"][1], '甲日生时戊辰 天财坐库㑹滋身富商巨贾田园盛 月')
        self.assertEqual(text_corrections["ocr-277"][1], '甲申日庚午时子辰年月㑹印亥卯年月身旺俱贵寅')
        self.assertEqual(text_corrections["ocr-278"][1], '戊不相逢 只恐功名不亨㤗\n 甲日乙亥时甲木亥上长')
        self.assertEqual(text_corrections["ocr-279"][1], '贵禄縁\n 乙日丙子时六乙䑕贵乙用庚为官死于子见')
        self.assertEqual(text_corrections["ocr-280"][1], '气化为福 不是寻常下贱㸔\n 乙日丁丑时食㑹财官丁为食庚为官已为')
        self.assertEqual(text_corrections["ocr-281"][1], '年月不见庚辛金贵秋生㸔地厚薄如生壬戌年月三')
        self.assertEqual(text_corrections["ocr-282"][1], '月文学儒官成卯贵子辰㑹官寅卯防印俱吉\n 【甲戌解')
        self.assertEqual(text_corrections["ocr-283"][1], '干支无水文进綉衣荣妻䕃子卯戌申酉年月二三品')
        self.assertEqual(text_corrections["ocr-284"][1], '财星作好命论年月子辰㑹官亥卯防印俱贵\n 【壬午明')
        self.assertEqual(text_corrections["ocr-285"][1], '显贵髙堂大厦君子封妻䕃子常人定好生涯堆金积')
        self.assertEqual(text_corrections["ocr-286"][1], '年月干透煞印者贵申子㑹官干透印比者贵如年月')
        self.assertEqual(text_corrections["ocr-287"][1], '卯辰巳申丑年月或午戌㑹局天干更透丙戌字主大')
        self.assertEqual(text_corrections["ocr-288"][1], '月冲亥丙旺库俱吉卯未㑹行金水运申子㑹行木火运俱贵【神白经云')
        self.assertEqual(text_corrections["ocr-289"][1], '谷多陈朽身无依倚不为㐫 有托妻贤而富厚\n 丁日辛')
        self.assertEqual(text_corrections["ocr-290"][1], '丁日生时乙巳 伤官暗里㑹枭神东方运地成虚秀 金')
        self.assertEqual(text_corrections["ocr-291"][1], '巳时春印夏旺秋财冬官㸔取用何如俱可论吉午未')
        self.assertEqual(text_corrections["ocr-292"][1], '午 日禄喜居时上遇柱中䑕兔癸无伤 少年腾逹青云')
        self.assertEqual(text_corrections["ocr-293"][1], '中年发福来运吉贵人相㑹合 安闲衣禄不须猜\n 丁日')
        self.assertEqual(text_corrections["ocr-294"][1], '午未戌身旺贵显若亥卯㑹未子辰防申俱以贵论\n 【乙')
        self.assertEqual(text_corrections["ocr-295"][1], '庚戌时生亥未年月三合㑹印贵子月煞印吉年月建')
        self.assertEqual(text_corrections["ocr-296"][1], '官不见刑冲破 早际风云㑹遇期\n 戊日丁巳时印绶遇')
        self.assertEqual(text_corrections["ocr-297"][1], '可期无破禹门三级浪 伫㸔一跃上天池\n 戊日时临丁')
        self.assertEqual(text_corrections["ocr-298"][1], '天时地利者贵年月申子㑹水寅午㑹火有旣济之妙辰月亦得')
        self.assertEqual(text_corrections["ocr-299"][1], '五六品贵须年月申子辰㑹财寅午印绶己酉伤官亥')
        self.assertEqual(text_corrections["ocr-300"][1], '日癸亥时午未月生化火㑹局高命春官煞混杂温饱')
        self.assertEqual(text_corrections["ocr-301"][1], '生俱大贵忌己巳月破败㐫死庚申月血光恶死壬子')
        self.assertEqual(text_corrections["ocr-302"][1], '庚寅年破败恶死己巳月㐫恶戊戌月孤单血死\n 【丁卯沈坤状元 壬寅府尹 辛亥侍郎壬子 原本传 甲辰 庚寅戊午朱之蕃状元尚书乙卯】\n 己亥日甲子时春夏财官生旺吉秋冬四季背禄逐马㐫寅月金火运郎官午月东')
        self.assertEqual(text_corrections["ocr-303"][1], '丑日庚午时寅月生贵夏㐫秋暴冬财旺子少【一云】总')
        self.assertEqual(text_corrections["ocr-304"][1], '酉丑月伤官伤尽吉寅月㐫暴夘未武职子未公侯【一云】主心狂肾病大贵\n 【癸亥俞大猷都督 戊申戴时中都宪己未 狡猾 乙丑】\n 【庚午都宪 癸亥进士 庚戌举人甲申 癸亥 癸未】\n 己亥日壬申时夘未三合㑹官干透印大贵戊子月财')
        self.assertEqual(text_corrections["ocr-305"][1], '帝旺吉亥戌寅夘土病死㐫酉辰三四品贵中年退闲')
        self.assertEqual(text_corrections["ocr-306"][1], '贵极人臣忌癸酉月破败㐫辛亥月血光甲子月夭\n 【丁')
        self.assertEqual(text_corrections["ocr-307"][1], '月破败刑丁酉月旺中刑㐫己丑月破败防\n 【丙戌大参')
        self.assertEqual(text_corrections["ocr-308"][1], '月行西运金方吉辛巳月㐫刑辛亥月孤夭\n 【戊辰国公 甲子李本阁老一云 乙丑郎中己未 辛木 壬午时 丁亥丙午进士 戊寅游戎 壬申解元 丙申进士庚寅 庚申 壬寅 丁酉】\n 庚戌日丙子时春夏生西南运秋月木火运俱贵忌乙巳月㐫破乙亥月官灾多㐫刑己丑月破败防戊戌月')
        self.assertEqual(text_corrections["ocr-309"][1], '者贵纯庚辰王侯不然极㐫若年月遇木火运再行极')
        self.assertEqual(text_corrections["ocr-310"][1], '偏官用财吉夏煞旺身衰㐫暴秋身煞俱旺巳酉丑月')
        self.assertEqual(text_corrections["ocr-311"][1], '东北运贵忌庚寅月刺面㐫癸未月受刑癸丑月破败')
        self.assertEqual(text_corrections["ocr-312"][1], '申月尸不全死壬子月孤㓙癸丑月防刑死\n 【己未彭凤')
        self.assertEqual(text_corrections["ocr-313"][1], '主贵破祖方发忌壬寅月㓙死辛巳月大败祖防庚戌')
        self.assertEqual(text_corrections["ocr-314"][1], '伤官生财夏行藏反复或㐫暴午未亦奇秋申酉身旺')
        self.assertEqual(text_corrections["ocr-315"][1], '运通亦贵\n 辛丑日癸巳时㐫别父母发福春夏吉秋冬㓙暴【一云】化贵戒酒\n 【戊戌魁')
        self.assertEqual(text_corrections["ocr-316"][1], '妻子春财旺夏吉秋平冬㓙暴酉午年月木火运风宪')
        self.assertEqual(text_corrections["ocr-317"][1], '寅 本年卒】\n 辛亥日戊戌时㐫狠机谋奸猾计较【一云】防')
        self.assertEqual(text_corrections["ocr-318"][1], '午月行西运六品子运败㐫若纯壬子羊刃贫㐫【一云】少年富三十五后艰辛末大富忌辛巳月㐫恶死辛亥月大防甲子月')
        self.assertEqual(text_corrections["ocr-319"][1], '忌己酉月孤单防丁亥月㐫刑恶死辛丑月刑\n 【壬辰曾')
        self.assertEqual(text_corrections["ocr-320"][1], '吉春平夏财禄秋吉中有㐫冬身旺须行南运方显\n 【辛')
        self.assertEqual(text_corrections["ocr-321"][1], '贵大显亥子水旺透壬主㐫午戌透戊煞旺亦防【一云')
        self.assertEqual(text_corrections["ocr-322"][1], '非大贵即大富忌甲辰月㐫刑孤丙申月㐫恶死己丑月刑【壬寅极品')
        self.assertEqual(text_corrections["ocr-323"][1], '戌亥大富贵寅夘孤辰巳㐫忌壬申月身不全㐫庚辰月㐫刑乙丑月失土防死\n 【癸亥徐阶探花阁老 乙酉太守 癸未安抚壬戌 戊子 甲子甲午序班丁丑】\n 癸酉日壬子时行藏进退少子难为妻家忌丙寅月不全尸死乙巳月大破㐫死丁酉月自缢死\n 【癸酉徐')
        self.assertEqual(text_corrections["ocr-324"][1], '万民英 撰\n 防命口诀\n 大凡㸔命先㸔月支有无财官方㸔其他月令为命也月取支神年取天干日取天干流嵗取天干大运取支神年为本日为主如月有正官及偏官而时又入他格只以月中取他格无用如月令全无可用方㸔他格【古歌云】三宫带格混')
        self.assertEqual(text_corrections["ocr-325"][1], '得子孙之力反此则否\n 凡㸔命以日干用为天元是以干为禄日支月攴用为地元是以支为命假如壬癸日己未月干支透出财官是也财官论原有原无地支原有财官天干不露出者不问若地支无财官只是天干透出虽行好运亦不济事㸔流年嵗君只用天元若行运虽重地支亦要㸔运天元人命柱中或有官')
        self.assertEqual(text_corrections["ocr-326"][1], '基少年便行官禄运多是㓜年拜命早发功名年月无财官日时有之则是自已成立人命以财官为本柱中但得其一亦可发福若四柱原无官星不入他格年月日时干支财多又行财旺运亦能成就功名以财旺自能生官须身旺方许年月无财官㓜年又行不好运多是出身卑微破祖伤父无见成之福凡命官煞混杂伤官合神重男子犯之躭迷酒色女人逢之不媒自嫁\n 凡㸔命专以日干为主取提纲所用之物为命譬月令以金木水火土为用但有一件取其节气先后轻重浅深成局破冲细加考究曰官曰印曰财曰煞曰食神曰伤官以此六法消息之逢官㸔财逢煞㸔印逢印㸔官取四者不偏不倚生克')
        self.assertEqual(text_corrections["ocr-327"][1], '言凡格以煞为重\n 凡命先㸔干神有无尅制支神有无')
        self.assertEqual(text_corrections["ocr-328"][1], '干昼生为本体夜生作化㸔五阴干夜生为本体昼生作化㸔六般阳命男犯禄鬼倒食')
        self.assertEqual(text_corrections["ocr-329"][1], '凶不贫即夭余以例推\n 凡㸔命伤官见官而早死七煞')
        self.assertEqual(text_corrections["ocr-330"][1], '倾五行之内宜细消详\n 凡㸔命五行太过不及固不为')
        self.assertEqual(text_corrections["ocr-331"][1], '互破无药可医遇空亡庶㡬嵗运亦忌之\n 凡命主本逢')
        self.assertEqual(text_corrections["ocr-332"][1], '富贵定知日后厌年华\n 凡㸔命取胎生旺库为四贵死')
        self.assertEqual(text_corrections["ocr-333"][1], '遇辰戌丑未皆以贵论\n 凡㸔命分五行生旺死絶如甲')
        self.assertEqual(text_corrections["ocr-334"][1], '天之道无可絶焉干支适㑹巳絶则更生凡遇此者忧喜未定如癸巳絶水得癸酉旺金扶之是谓絶水逢生尤为吉庆凡命带上死絶生旺库墓等不可就以所带言之须㸔月令以辨清浊清者有制')
        self.assertEqual(text_corrections["ocr-335"][1], '邜更在春生最吉若三合㑹木局全不须春生多主仁')
        self.assertEqual(text_corrections["ocr-336"][1], '父祖产业或客死他乡又㸔宅纳音与本命纳音相生')
        self.assertEqual(text_corrections["ocr-337"][1], '年亦须破须是为长方可㫁如丙子人得辛巳金为宅')
        self.assertEqual(text_corrections["ocr-338"][1], '元辰】干合无厄【六厄】旺无䘮【䘮门】衰无吊【吊客】妻无刃【羊')
        self.assertEqual(text_corrections["ocr-339"][1], '之谓也【或问】人生有始终㓛名富贵有一旦崛起忽然骤兴有始终剥落而中间奋发有半世淹蹇而晚年成就其故何也【荅曰】莫非命也其始终富贵乃柱中身主专旺其所用吉神或官印财食俱各带禄得令不偏不党无刑冲尅害出门行运歩歩皆吉故能成材能振耀绍前人之基业立当代之功名不招䜛谤不致伤害保其终始是')
        self.assertEqual(text_corrections["ocr-340"][1], '隆积财聚富但少贵耳再㸔行运何如如逢官禄旺乡富贵双全设有不幸财神脱局羊刃相逢更遇流年冲合羊刃财神尽伤元命衰絶羊刃生灾败亡必矣生死则以格局论如印绶见财行财运又兼死絶必入黄泉柱有比肩庶㡬有解正官见煞及伤官刑冲破害嵗运相并必死正财偏财见比肩分夺羊刃刼财嵗运冲合必死伤官之格财旺身弱官煞重见混杂冲刃嵗运又见必死制则伤残拱禄拱贵填实又见官煞刼亡冲刃嵗运重见即死日禄归时刑冲破害见七煞官星空亡冲刃必死煞官大忌嵗运相并必死其余诸格并忌煞及填实嵗运并临必死㑹诸凶神恶煞勾绞元辰亡神刼煞吊客墓病死宫诸煞九死一生财官太多身弱元犯七煞身轻如丙丁日干年月时庚辛加酉运或庚辛年必死甲乙日干庚辛月时夹杂年运见庚辛必死若有救则吉无救定凶五行神煞金多夭折水盛飘流木旺则夭土多痴呆火多愚顽太过不及作此论一不可拘二须敢㫁求其生死决定无疑至若五行生死如壬日生在二月行申运即死生在七月行邜运即死乃遇生怕死既死怕生造化与人事一也须并㸔之\n 尝谓人之生死年月日')
        self.assertEqual(text_corrections["ocr-341"][1], '重辛邜又逢隂又白鸡银䑕应辛酉庚子之祥白鸡在酉值太嵗不起之兆由上数事观之人之生死信前定矣哉若尹子常梦巳达午厄寅㓕后见蛇入穴得金坠马虎')
        self.assertEqual(text_corrections["ocr-342"][1], '三十八年生死隔风云际㑹总无常其后生死年月日')
        self.assertEqual(text_corrections["ocr-343"][1], '支中先分南北与东西次㸔三合内别认详六亲者从')
        self.assertEqual(text_corrections["ocr-344"][1], '相残为道无终火明木秀㓜年显达朝廷火炎水涸终')
        self.assertEqual(text_corrections["ocr-345"][1], '遇之则发资财变煞为官㓜嵗功名显达戊日午月火')
        self.assertEqual(text_corrections["ocr-346"][1], '六隂朝阳逢季月只作印㸔六壬趋艮逢亥月当以贫')
        self.assertEqual(text_corrections["ocr-347"][1], '倒焚死蛇伤土乃墙推土䧟五行煞重当如此详\n 【又曰')
        self.assertEqual(text_corrections["ocr-348"][1], '二徳禄位高迁飞刃伏刃㑹刃多凶伤官剥官见官为祸羊刃若逢印绶虽贵而残疾在身七煞无制逢官为祸而夀元不久三偏三正遇三竒贵居一品之尊四旺四生全四柱福在众人之上煞化为印早擢巍科财旺生官少受贻泽官煞同来要知扶官扶煞偏正相㑹须知合正合偏归禄月逢')
        self.assertEqual(text_corrections["ocr-349"][1], '喜者运干生于日干也但㸔有情无情合与不合凶防')
        self.assertEqual(text_corrections["ocr-350"][1], '求其意\n 【乃日干坐下首先㸔此地支与月支一位时支一位年支一位刑冲破害生尅比和何如主干喜忌何物得来不可视爲泛常不可顾盻】\n 月气浅深何者主权\n 【月建之下气候浅深五行之气是何干神正当此日天时之令五日一候之气一云徳秀有无】\n 地支至切党盛爲强\n 【地支乃四位支神至切者视天干爲尤切也要㸔何者为主干之宅舍何者为用神之基业何者力轻何者力重宅舎即得地之方基业即乘贵之所一㸔其力势冲起是何支神二㸔其力势拱起是何支神三㸔其力势刑起是何支神四㸔其力势合起是何支神五防地支綂摄此法是空中立有者也论地支冲拱刑合四件极切门庭一法只拿日干作主取用中间或吉神有刑冲凶煞有拱合其生旺休废交差不一难下手脚不如只详四个地支基址五气中何物最重将来品量却能耗散何神能生扶何神能冲合何神能变化何神然后却㸔日干属何五气与其最重之气綂摄何如便拿财官等物用神之气共前五气引于时座参较其物何者轻何者重义理调顺爲祥瑞反则即为乖戾矣如此已立定然后㸔其支气各有所喜所忌之')
        self.assertEqual(text_corrections["ocr-351"][1], '共有十般消息一件件要㸔衰旺轻重明晦广狭穷则究理尽处生何神尅何神刑何神合何神之类被坏之物得生之物主系何事物物推将去须要有依倚下落至无可奈何处便是转闗入何格调极处一转即是建防圆活参透却要定见下落断成器不成器何如】\n 有气者急有情者切\n 【有气乃当时也㸔八字内外明暗干支如六月中气大暑节土金旺相有气之类此爲至急余则否有情乃合气也如甲见己丙见辛丁见壬之类中间干支明暗有合皆取此为最切也一説非特合气有情吉神生我尅我亦为有情虚拱贵气生我尅我刑我合我亦无异也】\n 年干綂摄次防月时时如权衡分毫加减\n 【㸔年干所乘何支与我如何相摄爲切亦要引在有气贵地体局方大又㸔用神却系嵗君是何吉凶神煞若更用神与嵗君和全贵无疑次防月时二干之闗系不可竟作差慢不来扳搅柱中象数变化五气真假吉凶神煞俱当引归时座细分轻重分毫必须比较 又云太嵗一年之领袖诸神之主宰极有用处只因徐子平以日爲主专取财官悮了后人多少错㑹了义故曰年如称钩绾起')
        self.assertEqual(text_corrections["ocr-352"][1], '有辛未二字如影随形亦㸔辛未还是我家恩人却是讐人遥合即是支中所藏之神与彼所藏之气合也如申夘子巳亥午等类盖有其气类遥合事意自不放间矣】\n 体制须广大\n 【凡八字要㸔气象规模体势豁达天地')
        self.assertEqual(text_corrections["ocr-353"][1], '或不露亦犹抱虎而眠又㸔酉字有气无气可能驭服')
        self.assertEqual(text_corrections["ocr-354"][1], '虚薄不专被吉凶神煞播㺯随气动荡精神被其所役')
        self.assertEqual(text_corrections["ocr-355"][1], '日时带则紧】\n 十全贵气还㸔倚伏祸星一局凶神要识隠藏福气【贵气十分完备始终不坏中间寕无一件祸神隠藏凶煞之神往来繁杂其中却有一件福神隠隠深奥或虚夹遥合或刑出冲归亦系切当有意处不可便作满盘凶煞㸔只待何运扶起局中福气')
        self.assertEqual(text_corrections["ocr-356"][1], '仍自无合无生另立于缺䧟处者非异居同活则乞养寄生赘居外立】\n 党合双争妻财两义\n 【柱中如土党既多天时却系木旺抑扬之道在如何用不可便作两讐相竞若土不虚加厚木有气而露支音兼不刑害冲尅却能培养木秀成林爲用更竒我合者爲妻我尅者爲财世人但知我尅者总爲妻财纰缪未善又还㸔化象如何】\n 用神一字贵气')
        self.assertEqual(text_corrections["ocr-357"][1], '分毫之间便差远千里却㑹在合主扶佐何神至切为急事也】\n 善恶繁难时分众寡\n 【善恶二位俱众或错或杂但㸔时座聚众休旺聚寡休旺')
        self.assertEqual(text_corrections["ocr-358"][1], '繁或混或欠胜负或欠制䧏无分优劣忽一闲干非主')
        self.assertEqual(text_corrections["ocr-359"][1], '羊刃飞刃破宅大耗勾绞䘮吊官符病符死絶】\n 时座消')
        self.assertEqual(text_corrections["ocr-360"][1], '墓絶并煞刃来刑祸形恶㑹空赦领财官为体禄集福加\n 【墓絶死败至不足道若带有刃煞亡刼勾元等来冲刑尅窃日主并用神则祸患立侵矣月空天赦二神至吉善者天月徳天月合四神同㫁各司乃职主事若又系财')
        self.assertEqual(text_corrections["ocr-361"][1], '嵗运上扶起恶陷之气兼㑹煞局者即为沉沦防败悔吝破失之气类也甚则死无葬身之地须空亡并煞方㫁凡命之纳音常生常旺四')
        self.assertEqual(text_corrections["ocr-362"][1], '观坏尽之气\n 【生助滔滔者㸔转养之神何处为体用之')
        self.assertEqual(text_corrections["ocr-363"][1], '差慢而至停囚长智养病䘮身或系伤官之神无气不')
        self.assertEqual(text_corrections["ocr-364"][1], '官干神为用主禄最切却㸔日辰用为何神也马将亦')
        self.assertEqual(text_corrections["ocr-365"][1], '概亦有贵气俱全者不过㸔气厚气壮但中间欠清纯')
        self.assertEqual(text_corrections["ocr-366"][1], '恐亦被人杀戮也临事有㫁机变通利皆由凶煞之神不滞不塞辅佐用神有以使之然也若柱中象数纯和柔善气实则无纲常伦序之能虽有用神亦难也矣】\n 轩昂呼应原凭刃煞之威龌龊财丰尽带库墓之气【有贵气无刃煞辅佐不独临事无威勇作为殊欠相应合也有此刃煞扶贵必能做事立业果决有㫁有人名目卑微却发财禄')
        self.assertEqual(text_corrections["ocr-367"][1], '文又云食神或印此例同㫁凡泄气之神汗漫滔滔之势逺而有力聚而无依准上文】\n 江湖泛泛兮风飡雨宿罗网蒙蒙兮利锁名缰\n 【亥子为江湖若系财官禄马用神其气泛溢者多致道途生计披星带月其水泛泛其马刑冲方㫁辰巳为地网戌亥为天罗全者用神其上失地五气不能成象则利名碌碌无成如尘埃所罩昏雾所迷嵗运并临仍与日干尅害者夭亡】\n 水火动摇是非林里立身木金和恊义礼门庭发财【水火乃人间之动物犯此格多惹是非唇吻凡立身为事每于閙里出头鬬喋之中着脚若吉则有决䇿之机凶则有不雅之号金')
        self.assertEqual(text_corrections["ocr-368"][1], '池沐浴白虎空亡却有拱䕶柱中惟财库或财神专旺辅日主有情尅助者准上文】\n 嵗望阙门当近朝堂之职气冲第宅难依祖业之基【太嵗对为阙门有拱入格决主食禄职任皆近于朝堂要路之处嵗前第五位若是被冲更与日主非贵气生扶綂摄者决主祖上基业离破不能居住若乘官符并亡神主为官㫁没抄封犯破碎刼刃毁售')
        self.assertEqual(text_corrections["ocr-369"][1], '贵人徳神财官生旺者庶㡬】\n 坎离交㑹老醉秦楼象类清幽㓜登仙府\n 【子午上有干神钩合如壬子戊午之类戊合子癸壬合午丁或丁合壬癸合戊水火有情至老迷恋清则风流浊则卑贱五行之气至清成象况引于幽洁之地贵神归一不杂气纯清逺别无死絶等件恶神相犯准上文】\n 论文学业特精英长生徳秀殢酒惜花偏落魄身旺咸池\n 【长生帝旺四贵等处徳秀二神文学才能艺术特达精专出类㧞萃人也殢酒惜花日干旺于咸池之上一也本身自旺受沐浴之神尅者二也本身太旺沐浴更多福气散漫不聚三也】\n 妻遇比肩旺夺非是良人财因沐浴强争难辞淫浊【妻干或隠或显而切切遇比肩相近相亲其位被占夺又或比肩乘旺其妻必与外人私通不然娶婢妾娼妓为婚免此丑五行败处为沐浴又名桃花咸池煞一例同㫁其神若来乘势争财或财')
        self.assertEqual(text_corrections["ocr-370"][1], '上逢生旺则好仍以余神㑹合有情方贵一云我与妻')
        self.assertEqual(text_corrections["ocr-371"][1], '主必是再娶少年室女或㓜妾为妻若带禄贵赞助者')
        self.assertEqual(text_corrections["ocr-372"][1], '明见魁罡重集贵气同前㫁辰寅二位若遇正拱外拱')
        self.assertEqual(text_corrections["ocr-373"][1], '理所宜或顺以参考其否㤗之兆吉凶二象运元未萌')
        self.assertEqual(text_corrections["ocr-374"][1], '贱于反伤文章锦绣贵马㑹于学堂襟度宏濶水火合')
        self.assertEqual(text_corrections["ocr-375"][1], '陞迁岁尅运凶而人离财㪚大运危而生百祸流年吉以除千殃无絶至絶财命倾危求生得生名利称遂三合六合逢之吉重凶轻七煞四凶遇之祸深福浅职迁官进定因禄㑹之年产置田增必是合财')
        self.assertEqual(text_corrections["ocr-376"][1], '在变通祸福当察衰旺庶㡬知命君子共评\n 消息赋【珞')
        self.assertEqual(text_corrections["ocr-377"][1], '得失男迎女送否泰交居㑹吉㑹凶作用定矣】\n 运行则一辰')
        self.assertEqual(text_corrections["ocr-378"][1], '谓非阴阳五行之变也火䑕之毛绩而为布氷蚕之脂登而为爼此世之所知也神异经曰北方有层氷万里厚百丈有䑕重万斤毛长尺余在中藏')
        self.assertEqual(text_corrections["ocr-379"][1], '兴隆者源浊流清之谓也㓜年建旺而临老伶仃者裔苦根甘之谓也其乃较量运气穷究根源先察根基厚薄兼明运限始终虽未百发百中亦可希其八九大抵人命立年为尊其胎月日时资以次之故曰作四柱之君父为吉凶之主宰而立其年也明运气之本推虚实之基而取其月观安危之兆察苦乐之原而取其日定贵贱之本决生死之期而取其时辨㓜荫之始究未立之前而取')
        self.assertEqual(text_corrections["ocr-380"][1], '次而布之一辰三兽子人䑕蝠莺丑人牛蟹鳖寅人虎')
        self.assertEqual(text_corrections["ocr-381"][1], '吉卑凶逢灾自愈禄有三㑹灾有五期\n 【立年为尊其胎月日时资以次之大运为尊其太岁小运资以次之若遇本命与大运德合于建旺之乡其岁运日时凶而不能为咎大运与本命争战于死囚之地其岁运日时吉而未足为救故曰云云○禄有三㑹者长生帝旺库也其为至')
        self.assertEqual(text_corrections["ocr-382"][1], '巳为六虚亥为干天巳为㢲地巳乃南方之首神故云')
        self.assertEqual(text_corrections["ocr-383"][1], '若禄背之而去马逐之而㪚二者俱失所以守穷途而')
        self.assertEqual(text_corrections["ocr-384"][1], '丙寅时命生时于帝座上㑹同禄马兼甲申巳亥丙寅')
        self.assertFalse(text_map["summary"]["canonical_ready"])
        corrections = {(x["old"], x["new"]) for x in text_map["corrections"]}
        self.assertIn(("若失时防局卽韬光", "若失时䘮局卽韬光"), corrections)
        self.assertIn(("虽防𦕈之金亦不能制", "虽㣲𦕈之金亦不能制"), corrections)
        self.assertIn(("火强燥而防𦕈水既济以寛和", "火强燥而㣲𦕈水既济以寛和"), corrections)
        self.assertIn(("金水相停防合含光圆融皎洁", "金水相停㑹合含光圆融皎洁"), corrections)
        self.assertIn(("临老蛉仃者裔苦根甘", "临老伶仃者裔苦根甘"), corrections)
        self.assertIn(("阳刄者天上之防星人间之恶煞", "阳刄者天上之凶星人间之恶煞"), corrections)
        self.assertIn(("年干父兮支母日干巳兮支妻", "年干父兮支母日干己兮支妻"), corrections)
        self.assertIn(("飞防名天瞽支干无气主无目", "飞廉名天瞽支干无气主无目"), corrections)
        self.assertIn(("诸神之领防其説有二", "诸神之领袖其説有二"), corrections)
        self.assertIn(("大运虽防其小运却吉", "大运虽凶其小运却吉"), corrections)
        self.assertIn(("此小运又名行年不可不防醉醒", "此小运又名行年不可不究醉醒"), corrections)
        self.assertIn(("身旺官防财名寡合", "身旺官微财名寡合"), corrections)
        self.assertIn(("身坐比肩成比局当为防度新郎", "身坐比肩成比局当为几度新郎"), corrections)
        self.assertIn(("癸水相防为辛苦之经商", "癸水相会为辛苦之经商"), corrections)
        self.assertIn(("九宫防溺怕防运又怕防年", "九宫陷溺怕凶运又怕凶年"), corrections)
        self.assertIn(("或以申亥包酉戌防系天干何物", "或以申亥包酉戌看系天干何物"), corrections)
        self.assertFalse((C / "classics/bazi/sanming_tonghui_v1.json").exists())

    def test_sanming_pua_collation_progress(self):
        audit_path = ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_pua_audit.json"
        map_path = ROOT / "data/quarantine/public_domain_snapshots/daizhigev20/sanming_pua_collation.json"
        audit = json.loads(audit_path.read_text(encoding="utf-8"))
        mapping = json.loads(map_path.read_text(encoding="utf-8"))
        summary = mapping["summary"]
        self.assertEqual(audit["total_private_use_chars"], 524)
        self.assertEqual(audit["unique_private_use_chars"], 86)
        self.assertEqual(summary["confirmed_mappings"], 86)
        self.assertEqual(summary["confirmed_occurrences"], 524)
        self.assertEqual(summary["remaining_unique_codepoints"], 0)
        self.assertEqual(summary["remaining_occurrences"], 0)
        self.assertTrue(all(x["status"] == "confirmed" for x in mapping["mappings"]))
        self.assertIn(("U+E4BF", "琐"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA40", "𠒋"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E749", "渺"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECDE", "点"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED3F", "眩"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7B", "冢"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA85", "刑"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EB8E", "弦"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE60", "蒙"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA23", "胤"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED92", "算"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA1", "过"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E898", "瓜"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA6", "蓬"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA5B", "传"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA62", "备"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E8AA", "恶"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA26", "兮"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E9C7", "真"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAC0", "嗤"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAE6", "涂"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAF6", "压"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECD6", "熬"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7C", "寵"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEB8", "𫑗"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E59C", "燥"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBB8", "博"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBDE", "哲"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EDE6", "苑"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E3E5", "坷"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECEC", "管"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E10C", "𣷉"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E5AB", "𨽻"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED9E", "簪"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE26", "亏"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE6D", "博"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6A", "惕"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6C", "场"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBA5", "忘"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECCA", "烽"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED51", "瞽"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEA3", "递"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EED7", "开"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEE4", "徒"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EEE5", "隐"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF6B", "疡"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA7D", "凌"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EAA7", "段"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBC2", "惨"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ED94", "算"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF17", "鬓"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF33", "类"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF3F", "抟"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EF67", "参"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E5E0", "𦕈"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA9F", "𭅺"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E87D", "曄"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E9FC", "𡎊"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA3F", "充"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EA53", "含"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBDB", "𢫎"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECA6", "激"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EE9C", "逄"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E37B", "𤥣"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+E7E9", "崙"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+EBC1", "𢡟"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        self.assertIn(("U+ECC7", "𤇍"), {(x["codepoint"], x["replacement"]) for x in mapping["mappings"]})
        contextual = mapping["contextual_mappings"]
        self.assertEqual(len(contextual), 1)
        self.assertEqual(contextual[0]["codepoint"], "U+E7E8")
        self.assertEqual(contextual[0]["count"], 5)
        self.assertEqual(sum(x["count"] for x in contextual[0]["replacements"]), 5)
        self.assertIn(("韩命书", "韩𭹱命书"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("又恐天年多", "又恐天年多摩罗"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("为人巧虚诈", "为人惯巧虚诈"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        self.assertIn(("临老蛉者裔苦根甘", "临老蛉仃者裔苦根甘"), {(x["old"], x["new"]) for x in contextual[0]["replacements"]})
        singleton = next(x for x in mapping["mappings"] if x["codepoint"] == "U+EA62")
        self.assertEqual(singleton["count"], 1)
        self.assertEqual(len(singleton["source_anchors"]), 1)
        self.assertGreaterEqual(len(singleton["evidence"]), 2)
        self.assertFalse((C / "classics/bazi/sanming_tonghui_v1.json").exists())

    def test_hetu_luoshu(self):
        h = load("foundations/hetu_luoshu_v1.json")
        pairs = h["hetu"]["pairs"]
        self.assertEqual(len(pairs), 5)
        self.assertTrue(all(x["completing"] - x["generating"] == 5 for x in pairs))
        matrix = h["luoshu"]["matrix_south_up"]
        self.assertEqual(matrix, [[4,9,2],[3,5,7],[8,1,6]])
        rows = matrix
        cols = [list(x) for x in zip(*matrix)]
        diags = [[matrix[i][i] for i in range(3)], [matrix[i][2-i] for i in range(3)]]
        self.assertTrue(all(sum(line) == 15 for line in rows + cols + diags))
        self.assertEqual(len(h["luoshu"]["nine_palaces"]), 9)
        self.assertEqual(h["hetu"]["textual_attribution_status"], "UNVERIFIED")

if __name__ == "__main__":
    unittest.main()
